kakao/varlog

.github/workflows/ci.yaml, README.md
=> build: add ci

.github/workflows/ci.yaml, README.md
=> build: fix ci workflow

Makefile
=> chore: tidy makefile

.github/workflows/ci.yaml, internal/admin/admin_test.go, tests/it/management/management_test.go
=> fix: TestAdmin_GetStorageNode_FailedStorageNode

.github/codecov.yml, .github/workflows/ci.yaml, .gitignore, Makefile, README.md
=> build: add test coverage

.github/ISSUE_TEMPLATE/bug_report.md
Resolve: #34
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/35)
=> ci: add bug report template

.github/dependabot.yml
Resolve: #36
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/37)
=> ci: add dependabot settings

internal/admin/snmanager/manager.go
Resolve: #30
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/31)
=> fix: remove mutex in storage node manager of admin

.github/workflows/containers.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/48)
=> ci: change trigger for building container

internal/admin/snwatcher/snwatcher.go
Resolve: #45
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/49)
=> chore(admin): handle failed storage nodes concurrently

internal/storagenode/logstream/executor_test.go, internal/storagenode/logstream/replicate_client.go, internal/storagenode/volume/volume.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/50)
=> style: make typos correct

internal/metarepos/raft_metadata_repository_test.go, internal/storagenode/client/log_client_test.go, internal/storagenode/config.go, internal/storagenode/logstream/append.go, internal/storagenode/logstream/executor_test.go, pkg/util/units/units_test.go, tests/ee/local/demo/demo_test.go, tests/it/failover/failover_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/58)
=> style: fix lint warnings - ineffassign

internal/storagenode/logstream/executor_test.go, internal/storagenode/logstream/sequencer.go, internal/storagenode/logstream/writer.go, tests/it/testenv.go
See links:
- https://staticcheck.io/docs/checks/#S1000
- https://staticcheck.io/docs/checks/#S1001
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/59)
=> style: fix line warnings - gosimple

pkg/varlog/log.go, pkg/varlog/replicas_retriever.go, tests/ee/action_helper.go, tests/it/config.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/61)
=> style: fix lint warnings - deadcode

.golangci.yaml, cmd/varlogsn/flags.go, internal/metarepos/raft.go, internal/metarepos/raft_metadata_repository_test.go, internal/metarepos/raft_test.go, tests/it/testenv.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/63)
=> style: fix lint warnings - godot

.golangci.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/71)
=> style: remove deprecated linters

.github/workflows/containers.yaml
build: change triggering rule of building container
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/69)
=> build: change triggering rule of building container

.github/workflows/ci.yaml, .golangci.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/77)
=> ci: enable golangci-lint in github check

.github/workflows/release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/82)
=> ci: change token for release-please

internal/metarepos/options.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/66)
=> chore(mr): do not warn loopback raft host

build/Dockerfile
Add label to each dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/85)
=> build: add labels to dockerfiles

internal/storagenode/storagenode.go
Storage node loads log streams concurrently to decrease of duration of startup.
Resolves #138
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/139)
=> perf(storagenode): load log streams concurrently

internal/storagenode/logstream/executor_test.go, internal/storagenode/logstream/sync.go
This patch fixed a response of `/varlog.snpb.Management/SyncInit` to respect trimmed source replica.
The cause of the problem was that the destination replica replied` uncommittedLLSNBegin` of itself
as the starting position of synchronization regardless of the source replica's condition. When the
source replica has been trimmed, the first log position of the synchronization range can be larger
than the `uncommittedLLSNBegin` of the destination replica. In this case, the destination should set
its `uncommittedLLSNBegin` and `uncommittedLLSNEnd` to the first log position of the synchronization
range.
Note that this synchronization makes the destination replica's all logs be removed and filled with
the new logs from the source replica. To reflect that the source replica has no logs, the …
=> fix(storagenode): fix a response of SyncInit when source replica was trimmed

internal/storagenode/init.go, internal/storagenode/storagenode.go
Add gRPC logging to the storage node.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/144)
=> chore(storagenode): add grpc logging to storage node

internal/metarepos/storage.go
remove unnecessary report log 
Resolves #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/147)
=> refactor(mr): remove unnecessary report log

.github/workflows/codeql.yml
Add codeql setting.
See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/150)
=> ci: add codeql setting

internal/storage/storage.go, internal/storage/storage_test.go
This patch changes the method `internal/storage.(*Storage).Trim` not to remove the commit context.
According to the RFC (i.e., [20220915_commit_context.md](https://github.com/kakao/varlog/blob/main/docs/RFCs/20220915_commit_context.md)), the commit context is a pointer of the last commit message to help recover the log stream.
Thus, the trim that removes the log entries' prefix does not have to remove the commit context.
Moreover, removing a commit context while appending log entries is not trivial since Commit RPC can
change the commit context continuously.
Updates #125
=> feat(storage): change the trim not to remove the commit context

internal/storagenode/logstream/executor.go, internal/storagenode/logstream/executor_test.go
When reportCommitBase is invalid, which means that the commit context and log entries are
inconsistent, the log stream replica becomes sealing. The synchronization between replicas can
resolve it.
Updates #125
=> feat(storagenode): make log stream executor sealing when reportCommitBase is invalid

internal/storagenode/logstream/executor_test.go
Fix build error after merging #183.
=> test: fix build error after #183

.github/workflows/ci.yaml, go.mod
=> build: upgrade golang 1.19

internal/metarepos/storage.go
add logs to track status of reports.
Resolves #212 
=> refactor(metarepos): add log for report status

cmd/benchmark/benchmark.go, internal/benchmark/benchmark.go, internal/benchmark/config.go
This patch adds optional functions to the benchmark.
=> refactor(benchmark): add optional functions to benchmark

pkg/varlog/log_mock.go, proto/snpb/mock/snpb_mock.go
This patch adds missing mock files updated by #240 and #242.
Resolves #240 #242
=> fix(storagenode,client): add missing mock files

tests/it/failover/failover_test.go
Fix test helper from `require.Condition` to `require.Eventually`.
=> test: fix test helper

.github/workflows/ci.yaml
=> ci: unify test and coverage test

internal/benchmark/model/execution/execution.go, internal/benchmark/model/executiontrigger/execution_trigger.go, internal/benchmark/model/macro/macrobenchmark/macrobenchmark.go, internal/benchmark/model/macro/result/result.go, internal/benchmark/model/macro/target/target.go, internal/benchmark/model/macro/workload/workload.go
This patch fixed SQL to create a new row if it does not exist and fetch the row.
=> fix(benchmark): create a new row and get the row from the tables

internal/benchmark/model/macro/target/target.go, internal/benchmark/model/macro/workload/workload.go
Fix SQL statements for target and workload.
=> fix(benchmark): fix sql for target and workload

internal/admin/admin.go, internal/admin/mrmanager/manager.go
return an explicit error code for every case of UpdateLogStream
Resolves #310 
=> refactor(admin): return an explicit error code for every case of UpdateLogStream

internal/storagenode/logstream/executor_test.go, internal/storagenode/logstream/subscribe.go
When the Subscribe API tried to scan ranges with no log entries below the global high watermark, it
was blocked until another commit message came. See detail #375.
This patch adds boundary checks to the
`internal/storagenode/logstream.(*Executor).SubscribeWithGLSN`.
- If the exclusive end of subscribe range is less than or equal to the local low watermark but
greater than the global low watermark, the API returns an empty result.
- If the subscribe range is between the local and global high watermarks, the API returns empty
results.
- While scanning log entries, if the end of the range is between the local high watermark and global
high watermark, the end will be replaced with the local high watermark.
Resolves #375
=> fix(storagenode): subscribe empty range below the global high watermark

internal/storagenode/logstream/append.go, internal/storagenode/telemetry/metrics.go
This PR changed durations in metrics from milliseconds to microseconds.
=> refactor(storagenode): change durations in metrics from milliseconds to microseconds

internal/admin/replica_selector.go, internal/admin/replica_selector_test.go
It adds a new replica selector, `randomReplicaSelector`. It chooses storage nodes and paths
randomly.
Updates #393
=> feat(admin): random replica selector

cmd/varlogmr/metadata_repository.go
allow setting commitTick
Resolves #519 
=> fix(metarepos): allow setting commitTick

cmd/varlogsn/varlogsn.go, internal/storage/config.go, internal/storage/storage_test.go
Fix typo from WithMetrisLogInterval to WithMetricsLogInterval.
=> chore(storage): fix typo WithMetricsLogInterval

internal/storage/recovery_points.go, internal/storage/storage_test.go
Change types of First and Last of RecoveryPoints from LogEntryMeta to LogSequenceNumber.
=> refactor(storage): change types of First and Last of RecoveryPoints from LogEntryMeta to LogSequenceNumber

pkg/types/types.go, pkg/types/types_test.go
Remove unused function NewClusterIDFromUint.
=> refactor: remove unused function NewClusterIDFromUint

internal/admin/admin.go
It fixes a transient error caused by fetching cluster metadata too lately while handling AddStorageNode. This PR lets the AddStorageNode RPC handler fetch the cluster metadata forcibly and wait for them to be updated. Although it isn't a critical error and can be resolved through a simple retry, it is resolved quickly by fetching the cluster metadata.
Error example:
```
--- FAIL: TestVarlogAppend (5.38s)
controller.go:62:
Error Trace:    /home/runner/work/varlog/varlog/tests/ee/controller/controller.go:62
/home/runner/work/varlog/varlog/tests/ee/cluster/local/cluster.go:238
/home/runner/work/varlog/varlog/tests/ee/cluster/local/cluster.go:63
/home/runner/work/varlog/varlog/tests/ee/ee_test.go:32
Error:          Received unexpected error:
exit status 255
Test:           TestVarlogAppend …
```
=> fix(admin): refresh cluster metadata while adding storage node

pkg/varlogtest/admin.go, pkg/varlogtest/varlogtest_test.go, proto/varlogpb/metadata.go
This PR adds a validator to the AddLogStream API in the varlogtest.
Especially the validator checks the replicas requested. For example, if they
have duplicate storage nodes, their length is less than the replication factor,
or they have unknown storage nodes.
Although the real varlogadm server's AddLogStream API is tested, the same thing
in the varlogtest package has not been tested, surprisingly. To fix it, all the
implementations in the `internal/admin` and `pkg/varlogtest` have to use the
same test suite. However, it will lead to a quite big refactoring. Therefore,
this PR fixes the bug and adds some unit tests in the varlogtest package.
Later we will revisit it to resolve #592.
=> fix(varlogtest): validate log stream descriptor to create it

.golangci.yaml, Makefile, cmd/varlogadm/cli.go, cmd/varlogcli/varlogcli.go, cmd/varlogctl/cli.go, cmd/varlogmr/metadata_repository.go, cmd/varlogsn/cli.go, internal/buildinfo/buildinfo.go
This PR adds the version to the daemons. It infers the correct version from the git's latest tag.
=> feat(all): add version to the daemons

pkg/util/units/units.go, pkg/util/units/units_test.go
This PR makes pkg/util/units.FromByteSizeString discriminates SI and IEC standards while parsing byte size string.
Resolves #661
=> feat: pkg/util/units.FromByteSizeString respects SI and IEC standards

internal/storage/scanner.go
This PR substantially enhances the performance of GLSN-based log scanning in
Varlog's storage layer by shifting from point lookups to an iterator approach.
While introducing a minimal overhead of one additional object allocation, this
modification significantly reduces operation times and increases throughput for
larger scan sizes. The slight increase in object allocation is a small trade-off
for the significant performance gains achieved, as demonstrated by the
benchmark.
```
goos: darwin
goarch: amd64
pkg: github.com/kakao/varlog/internal/storage
cpu: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
│    base     │                diff                 │
│   sec/op    │   sec/op     vs base                │
Storage_ScanWithGLSN/numLogs=1-8      2.298µ ± 1%   3.088µ ± 1%  +34.36% (p=0.000 n=20) …
```
=> perf(storage): improve scanning with GLSN

cmd/benchmark/test_command.go, go.mod, go.sum, internal/benchmark/loader.go, vendor/github.com/google/gops/LICENSE, vendor/github.com/google/gops/agent/agent.go, vendor/github.com/google/gops/agent/sockopt_reuseport.go, vendor/github.com/google/gops/agent/sockopt_unsupported.go, vendor/github.com/google/gops/internal/internal.go, vendor/github.com/google/gops/signal/signal.go, vendor/modules.txt
This pull request adds the gops agent into the benchmark tool, making it easier
to diagnose.
Refs:
- <https://github.com/google/gops>
=> feat(benchmark): use gops to diagnose benchmark tool

cmd/varlogadm/testdata/varlogadm.ct, cmd/varlogmr/testdata/varlogmr.ct, cmd/varlogsn/testdata/varlogsn.ct, go.mod, go.sum, vendor/github.com/urfave/cli/v2/godoc-current.txt, vendor/github.com/urfave/cli/v2/help.go, vendor/github.com/urfave/cli/v2/template.go, vendor/modules.txt
=> build(deps): bump github.com/urfave/cli/v2 from 2.27.2 to 2.27.3

.github/workflows/release.yaml, release-please-config.json
=> ci(release): move from google-github-actions/release-please-action to googleapis/release-please-action

proto/snpb/log_io_test.go
Add missing test for `proto/snpb.ValidateTopicLogStream`.
=> test: add missing test for proto/snpb.ValidateTopicLogStream

internal/metarepos/report_collector.go
sampleTracer.report is called as many times as UncommittedLLSNLength and filtered by sample rate. Normally, there is no problem, but if the commit processing is delayed in varlogsn, a report with a large UncommittedLLSNLength may come. In this case, the load on reportCollector increases. Improved so that it can be called at each sample rate.
Resolves #1013
=> perf(reportCollector): reduce calling sampleTracer.report

.github/workflows/backport.yaml
This PR adds release-please action settings for backporting.
=> ci: release-please setting for backporting

pkg/util/telemetry/metric_provider.go
This commit enables Varlog to support both new and deprecated OpenTelemetry
runtime metrics.
Previously, Varlog only supported the deprecated runtime instrumentation. This
change ensures backward compatibility by simultaneously setting the
`OTEL_GO_X_DEPRECATED_RUNTIME_METRICS` environment variable and using the new
version.
This enhancement allows Varlog to leverage the latest OpenTelemetry features
while maintaining compatibility with older versions, collecting more
comprehensive runtime metrics.
Backport: #999
=> feat(telemetry,backport): Support both new and deprecated OpenTelemetry runtime metrics

pkg/util/telemetry/metric_provider.go
This commit enables Varlog to support both new and deprecated OpenTelemetry
runtime metrics.
Previously, Varlog only supported the deprecated runtime instrumentation. This
change ensures backward compatibility by simultaneously setting the
`OTEL_GO_X_DEPRECATED_RUNTIME_METRICS` environment variable and using the new
version.
This enhancement allows Varlog to leverage the latest OpenTelemetry features
while maintaining compatibility with older versions, collecting more
comprehensive runtime metrics.
backport: #999
=> feat(telemetry): Support both new and deprecated OpenTelemetry runtime metrics

.github/workflows/backport.yaml, .github/workflows/release.yaml, release-please-config.json
Updated the release-please settings to improve the release process.
- BREAKING CHANGE only bumps semver minor if version < 1.0.0
(bump-minor-pre-major: true)
- feat commits bump semver patch instead of minor if version < 1.0.0
(bump-patch-for-minor-pre-major: true)
=> ci(release-please): update release-please configuration

internal/admin/snmanager/manager.go
This patch allows sealing replicas in parallel, so that even if a particular storagenode is delayed, seal requests can still be sent to other storagenode.
Resolves #1077 
=> fix(admin): seal replicas in parallell

pkg/util/telemetry/metric_provider.go
This change enhances the precision of runtime metric measurements. It updates
`process.runtime.go.gc.pause_ns` boundaries to improve granularity:
- 50us to 1ms (50us steps)
- 5ms to 95ms (5ms steps)
- 100ms to 1s (100ms steps)
=> refactor(telemetry): improve histogram boundaries for enhanced metric precision

internal/storagenode/telemetry/metrics.go
Refines the precision of the following metrics by introducing finer-grained
boundaries:
- `log_rpc.server.duration`
- `log_rpc.server.log_entry.size`
- `log_rpc.server.batch.size`
`log_rpc.server.duration`:
- Ranges from 100 to 1000 microseconds with a step of 100us
- Ranges from 2 to 100 milliseconds with a step of 2ms
- Ranges from 150 to 3000 milliseconds with a step of 50ms
`log_rpc.server.log_entry.size` and `log_rpc.server.batch.size`:
- Ranges from 100 to 1000 bytes with a step of 100B
- Ranges from 5 to 100 kilobytes with a step of 5KB
- Ranges from 150 kilobytes to 1 megabyte with a step of 50KB
- Ranges from 1.5 to 20 megabytes with a step of 500KB
These changes improve granularity, enabling more precise metric tracking and
analysis.
=> refactor(metrics): enhance precision for RPC duration and size metrics

internal/reportcommitter/client.go
This commit updates the Client interface documentation to specify its
concurrency usage rules. By defining these rules, the previously used mutexes
are no longer required and have been removed to simplify the implementation.
Removing the mutexes is safe for the current codebase since metadata
repository's reportCollectExecutor uses the reportcommitter Client exclusively.
=> refactor(reportcommitter): clarify Client concurrency and remove mutexes

internal/metarepos/report_collector.go, internal/metarepos/report_collector_test.go, proto/mrpb/raft_metadata_repository.go
This change removes the creation of `StorageNodeUncommitReport`, which was
unnecessary and added complexity. Its cost was mitigated by `sync.Pool`, but it
is no longer needed. The code now directly uses slices of
`LogStreamUncommitReport` for improved simplicity and maintainability.
This change improves performance significantly, reducing memory allocations by
100% in some cases and execution time by up to 75%, as shown below:
```txt
goos: darwin
goarch: arm64
pkg: github.com/kakao/varlog/internal/metarepos
cpu: Apple M3 Max
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
SwapReport/getAndSavePtr-14    44.95n ± 1%   10.90n ± 0%  -75.75% (p=0.000 n=20)
SwapReport/getAndSave-14       45.60n ± 0%   11.30n ± 0%  -75.21% (p=0.000 …
```
=> perf(metarepos): remove unnecessary creation of StorageNodeUncommitReport

internal/metarepos/reportcommit_test.go
This change fixes a flaky test issue in `TestReportCommit`. The test
occasionally failed with an "index out of range" error because the `GetReport`
request was processed by the mock storage node after the last `CommitBatch` in
`reportsCommits`. This was not an issue with the storage node or metadata
repository but a problem with the test logic.
Example failure log:
```txt
2025-05-02T06:55:51.0691510Z panic: runtime error: index out of range [5] with length 5
2025-05-02T06:55:51.0691890Z
2025-05-02T06:55:51.0692238Z goroutine 31718 [running]:
2025-05-02T06:55:51.0692988Z github.com/kakao/varlog/internal/metarepos_test.TestReportCommit.func2({0x1da8510, 0xc000120bf0})
```
The fix ensures that the test logic handles cases where the version index
exceeds the available range by using the last …
=> test: fix flaky TestReportCommit

pkg/mrc/mrconnector/mr_connector_test.go
This commit refactors the TestConnectorRemovePeer test to use EventuallyWithT
from the testify package for improved assertion clarity. It also reduces waiting
time to speed up test execution.
=> test(mrc): refactor TestConnectorRemovePeer to use EventuallyWithT

internal/storagenode/logstream/replicate_client.go
This change updates the replicator's loop to process all pending tasks in the
queue during each iteration, reducing runtime scheduling overhead.
=> perf(storagenode): process all pending tasks per iteration in replicator loop

pkg/varlog/subscribe.go
This commit renames `subscribedLogEntriesQueue` to `dispatchQueue` in the
`pkg/varlog` package. The new name better reflects the queue's role: it buffers
`SubscribeResult` items and ensures they are delivered in order to the user
callback, starting from the desired GLSN. The previous name was verbose and less
clear about its purpose. The refactor also removes the unused fields: `end` and
`closer`.
Update: #654
=> refactor(client): rename subscribedLogEntriesQueue to dispatchQueue

internal/metarepos/raft_metadata_repository_test.go
This commit refactors the methods of the `testMetadataRepoCluster` helper struct
to improve error handling and test stability.
Key changes include:
- Modifying method signatures to accept a `*testing.T` argument.
- Replacing `error` return values with testify assertions for explicit error and
precondition checking.
- Removing `//nolint:errcheck` comments and ensuring all potential errors are
now handled within the helper methods.
=> refactor(metarepos): improve error handling in testMetadataRepoCluster helper

internal/storage/store.go
This commit refactors the Pebble event listener initialization and switches to
using the structured logger.
Previously, the event listener was created using
`pebble.MakeLoggingEventListener`, and then unwanted event handlers were set to
nil. This approach is brittle, as future changes in the Pebble API could
introduce new events that would be logged unintentionally. The new
implementation explicitly initializes a `pebble.EventListener` struct, making it
more maintainable and robust against upstream changes.
Additionally, the new event listener now use the `zap.Logger` instead of
`zap.SugaredLogger`. This improves performance by avoiding reflection and string
formatting overhead.
=> refactor(storage): improve Pebble event listener and logger
