Makefile

This patch fixes to use of the correct docker-protobuf container, which
is `ghcr.io/kakao/varlog-protobuf:0.1.0`.
Resolves #5

build: use docker-protobuf

---

internal/admin/snwatcher/config.go
internal/admin/snwatcher/snwatcher.go

This patch adds a timeout in which the admin handles failed storage
nodes. Currently, the default timeout is 1 second.
The storage node watcher of the admin handles failed storage nodes
sequentially. We need to improve it to be run concurrently.
Resolve: #29
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/33)

fix(admin): add handler timeout for failed sn

---

tests/it/testenv.go

This patch fixed the lint error which is https://staticcheck.io/docs/checks#S1005.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/51)

style: remove unnecessary blank identifiers from assignments

---

internal/metarepos/report_collector.go
tests/it/cluster/cluster_test.go
tests/it/management/management_test.go

**Send empty commit result to new logstream**
When a new logstream is created, metadata repository sends an empty commit result 
containing the version so that the logstream knows the current version.
Resolves #52
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/65)

fix(mr): let newbie logstream know cur version

---

cmd/varlogmr/app/metadata_repository.go
internal/admin/admin.go
internal/admin/snmanager/manager.go
internal/metarepos/raft.go
internal/metarepos/raft_metadata_repository.go
internal/metarepos/raft_metadata_repository_test.go
internal/metarepos/raft_test.go
internal/metarepos/report_collector.go
internal/metarepos/report_collector_test.go
internal/metarepos/storage.go
internal/metarepos/storage_test.go
pkg/mrc/mrconnector/mr_connector_test.go
pkg/util/fputil/dirsize.go
pkg/util/log/log_test.go
pkg/util/syncutil/onlyonce_test.go
pkg/varlog/allowlist.go
pkg/varlog/metadata_refresher.go
pkg/varlog/subscribe.go
pkg/varlog/trim.go
tests/it/failover/failover_test.go
tests/it/mrconnector/mr_connector_test.go
tests/marshal_test.go

Fix lint warnings related to the unhandled error.
Some of the warnings were fixed but others were skipped.
We can find skipped warnings by running grep ` //nolint:errcheck // TODO: Handle an error returned.`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/72)

style: fix lint unhandled error

---

internal/metarepos/raft_test.go
internal/storagenode/logstream/replicate_task.go
internal/storagenode/logstream/sequencer.go
internal/stress/stress.go
internal/varlogcli/append.go
internal/varlogctl/controller_test.go
pkg/rpc/rpc_conn.go
pkg/util/fputil/dirsize_test.go
pkg/util/fputil/filepath.go
pkg/util/testutil/conveyutil/conveyutil.go
pkg/varlog/options.go
pkg/varlogtest/log.go
pkg/varlogtest/varlogtest_test.go
tests/ee/k8s/vault/vault.go
tests/it/cluster/client_test.go
tests/it/management/management_test.go
tests/it/testenv.go

This PR resolves lint warnings about staticcheck.
It skips lint warnings related to #73, #74, and #75.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/76)

style: resolve lint warnings - staticcheck

---

cmd/varlogadm/cli.go
cmd/varlogadm/flags.go

This change adds a new flag `--loglevel` to varlogadm. It specifies the log level of the admin server.
Its default value is "info". Possible values are "debug", "info", "warn", "error", "dpanic", "panic", and "fatal".
Resolves #79
Links:
- https://github.com/uber-go/zap/blob/0d6a75bccff91a3106f193c9e4e1678738a63f9d/zapcore/level.go#L35-L52
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/80)

feat(admin): add `--loglevel` flag to varlogadm

---

cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go

This patch adds new CLI flags to the varlogsn:
- `--logfile-retention-days`: Durations in days the log files are retained.
- `--logfile-compression`: Whether log files are compressed.
- `--loglevel`: Log level, for instance, "debug", "info", "warn", "error", "dpanic", "panic", and
"fatal".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/83)

feat(sn): add CLI flags to varlogsn

---

internal/metarepos/raft_metadata_repository.go
internal/metarepos/storage.go

This PR fixes the handling of duplicated RegisterLogStream command.
Some commands proposed with guarantee options can be applied multiple times. 
UncommitReports was reset because MR did not handle the duplicate RegisterLogStream command. 
This caused subsequent reports to be ignored.
Resolves #62 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/86)

fix(mr): handle duplicated RegisterLogStream(#62)

---

bin/start_varlogsn.py
bin/tests/test_start_varlogsn.py
internal/admin/stats/repository.go
internal/varlogctl/controller_test.go
testdata/varlogctl/getstoragenode.1.golden.json

To fix an exception in the `start_vartsn.py`, it sets an empty slice to the `proto/snpb.(StorageNodeMetadataDescriptor).LogStreamReplicas` when there is no log stream replicas in the storage node.
Resolves #88
When there was no log stream replica in a storage node, the JSON field `logStreams` in the GetStrorageNode response was null.
It can cause an exception while accessing the field after decoding the response, for example `TypeError: 'NoneType' object is not iterable`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/90)

fix list storagenodes json exception

---

bin/start_varlogsn.py
internal/admin/stats/repository.go
internal/varlogctl/storagenode/storagenode.go

Set empty list to `logStreams` in the GetMetadata reponse when it is null.
Resolves #88.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/94)

fix start varlogsn

---

pkg/util/fputil/dirsize.go

Add error handling to WalkFunc in filepath.Walk in `pkg/util/fputil.DirectorySize` to avoid panic.
Resolves #91.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/92)

fix dirsize

---

internal/storage/storage.go
internal/storage/testing.go

This patch fixed the missing use of the sync option of `internal/storage.(*Storage)`. The sync operation of WAL can be deferred by using the option `WithoutSync`.
Resolves #102
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/103)

fix(storage): apply WithoutSync option correctly

---

internal/admin/admerrors/errors.go
internal/admin/admin.go
internal/admin/mrmanager/manager.go
internal/storagenode/client/management_client.go
pkg/varlog/admin.go
pkg/varlogtest/admin.go
pkg/verrors/errors.go
proto/vmspb/admin.pb.go
proto/vmspb/admin.proto
tests/it/admin_test.go

This patch adds gRPC codes to errors returned from RPC `proto/vmspb.UpdateLogStream. It helps
clients to clarify kind of errors and decides if it is retriable.
Resolves #107
Refs: https://grpc.github.io/grpc/core/md_doc_statuscodes.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/109)

feat(admin): use gRPC codes to clarify errors returned from `proto/vmspb.UpdateLogStream` RPC

---

internal/admin/admin.go
internal/admin/admin_test.go
internal/admin/stats/repository.go
internal/admin/stats/repository_mock.go
pkg/varlog/admin.go
pkg/verrors/errors.go
proto/vmspb/admin.pb.go
proto/vmspb/admin.proto
tests/it/failover/failover_test.go
tests/it/management/management_test.go
tests/it/testenv.go

RPCs GetStorageNode and ListStorageNodes should contain all storage nodes registered to the cluster
even if the admin server is just restarted.
Previously, if the admin server was restarted the stats repository of the admin was flushed, thus,
it had a problem that the RPCs do not return all storage nodes after restarting.
This patch fixes the problem by using the cluster metadata fetched from the metadata repository. If
the metadata repository is not reachable transiently, the RPCs return an error with the status code
`Unavailable`.
Resolves #106
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/110)

fix(admin): contains all storage nodes registered to the cluster

---

internal/admin/admin.go
pkg/varlog/admin.go
tests/it/failover/failover_test.go

\#110 fixed the #106. However, it might not contain the log stream replicas in the result of
ListStorageNodes when the admin has been just restarted.
This patch uses the cluster metadata even if there is no information about the storage node in the
stats repository.
Resolves #106
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/112)

fix(admin): add log stream replicas to result of ListStorageNodes

---

.github/workflows/ci.yaml

Uploading coverage report fails sometimes.
According to the log, this patch set a token for codecov although the token is not necessary for a public repository.
```
[2022-09-05T15:18:53.760Z] ['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/118)

ci: add codecov token

---

internal/storagenode/config.go
internal/storagenode/storagenode_test.go

This makes all volumes of storage node absolute even if user sets the flag `--volumes` as relative.
The absolute paths make more explicit than relative path, thus storage node should manage data directories as absolute path.
Resolves #116
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/117)

fix(storagenode): make volumes absolute

---

internal/storagenode/storagenode_test.go

This patch makes test not delete `internal/storagenode/testdata/relative_volume/.keep`.
Hidden file `internal/storagenode/testdata/relative_volume/.keep` prevents
`internal/storagenode/testdata/relative_volume` from deleting since git is
ignore empty directory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/123)

test(storagenode): do not delete ".keep" file from `internal/storagenode/testdata/relative_volume`

---

proto/varlogpb/metadata.go
proto/varlogpb/metadata_test.go

This patch removes unused function - `proto/varlogpb.DiffReplicaDescriptorSet`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/131)

refactor: remove unused helper function for replica descriptor

---

internal/admin/admin.go
internal/admin/admin_test.go

This patch makes the RPC `/varlog.vmspb.ClusterManager/UpdateLogStream` succeed
when the replicas are already updated.
Resolves #126
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/137)

fix(admin): succeed to `/varlog.vmspb.ClusterManager/UpdateLogStream` when already updated

---

internal/storagenode/init.go

Do not log payload of `/varlog.snpb.Management/AddLogStreamReplca` by using the
package `github.com/grpc-ecosystem/go-grpc-middleware/logging/zap`.
It seems that the package does not work well with gogoproto's time.
```
panic: message *time.Time is neither a v1 or v2 Message [recovered]
panic: message *time.Time is neither a v1 or v2 Message
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/145)

fix(storagenode): do not log payload of `/varlog.snpb.Management/AddLogStreamReplca`

---

internal/metarepos/dummy_storagenode_client_factory_impl.go

Fix CodeQL issue - fix bad integer casting.
See https://github.com/kakao/varlog/security/code-scanning/1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/151)

test: fix bad int casting in `internal/metarepos.(*DummyStorageNodeClientFactory).GetManagementClient`

---

docs/RFCs/20220915_commit_context.md

RFC draft on improving commit context
Ref: #125
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/149)

docs: draft on improving commit context

---

internal/storagenode/logstream/executor.go
internal/storagenode/storagenode.go
internal/storagenode/storagenode_test.go

Remove the data directory when handling RemoveLogStreamReplica.
Resolves #157
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kakao/varlog/158)

fix(storagenode): remove data directory in removing log stream replica

---

internal/storagenode/logstream/executor.go
internal/storagenode/logstream/testing.go
internal/storagenode/storagenode_test.go
tests/it/management/management_test.go

Previously, a log stream replica in the learning state sent reports to the metadata repository, and
the log stream replica had to use commit contexts sent from the source replica.
However, the source cannot do that in a future patch because replicas in a log stream will store the
latest commit context rather than all commit contexts.
This patch slightly changes the report's behavior in a log stream replica, not to send it while in a
learning state. When the log stream replica copies the data from the source replica, it will not
send the report.
Updates #125
RFC: https://github.com/kakao/varlog/blob/main/docs/RFCs/20220915_commit_context.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

feat(storagenode): replica in the learning state does not report to a metadata repository

---

internal/metarepos/dummy_storagenode_client_factory_impl.go
internal/metarepos/raft_metadata_repository.go
internal/metarepos/raft_metadata_repository_test.go
internal/metarepos/report_collector.go
internal/metarepos/report_collector_test.go
proto/snpb/log_stream_reporter.go

This patch allows the metadata repository to ignore invalid reports from storagenode. Since storagenode is changed 
not to save the commit context, an invalid report may be given in the learning state.
Updates #125 

feat(metarepos): ignore invalid report

---

internal/storagenode/logstream/executor.go
internal/storagenode/logstream/executor_test.go
internal/storagenode/logstream/sync.go

When a log stream replica handles SyncInit, it can be prone to mutate the replica's state too early.
It should change the state after checking a valid sync range. It also updates the version, high
watermark, and uncommittedLLSNBegin with zeros to denote that the replica sends an invalid report
while the learning phase.
The replica checks whether it is in the learning phase at the end of method
`internal/storagenode/logstream.(*Executor).Report` to minimize the probability of concurrency
issues mentioned in #159.
Refs
- https://github.com/kakao/varlog/pull/159#issuecomment-1254917165

fix(storagenode): fix error-prone state management of SyncInit and Report

---

internal/storage/commit_batch.go
internal/storage/encode.go
internal/storage/encode_test.go
internal/storage/storage.go
internal/storage/storage_test.go

This patch adds a new approach to storing a commit context, only the latest commit context. It does
not remove the previous method to keep tests succeeding; we will remove it later.
Updates #125

feat(storagenode): store only the latest commit context for every commit

---

pkg/varlog/operations.go
pkg/varlog/options.go

This PR allows the user to append within specific LogStreams.
Resolves #171 

feat(client): add allowed logstream list option to varlog client

---

pkg/varlog/operations.go

Varlog client deny if the lsid is not in the received allowed list.
Resolves #175

feat(client): deny lsid if not allowed

---

internal/storage/append_batch.go
internal/storage/storage.go
internal/storage/storage_test.go
internal/storage/testing.go

There were already two kinds of batches in storage:
- The write batch saves only data keyed by the LLSN.
- The commit batch saves only the commit context and GLSN, and the commit context must exist.
This patch introduces a new batch type - append batch. The append batch saves both log entries and
a commit context. However, it is not necessary to keep the commit context. During synchronization,
the append batch must store log entries from a destination replica.
Updates #125

feat(storage): introduce append batch

---

internal/storagenode/logstream/committer.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/executor_test.go
internal/storagenode/logstream/log_stream_context.go
internal/storagenode/logstream/log_stream_context_test.go
internal/storagenode/logstream/sync.go
internal/storagenode/logstream/sync_test.go
proto/varlogpb/metadata.go

This patch unifies two similar fields -
`internal/storagenode/logstream.(reportCommitBase).uncommittedLLSNBegin` and
`internal/storagenode/logstream.(logStreamContext). localWatermarks.high`. Usually,
uncommittedLLSNBegin is the next of localHighWatermark. Thus, the uncommittedLLSNBegin can infer
the localHighWatermark. The unified field is `internal/storagenode/logstream.(reportCommitBase).uncommittedBegin`.
The reason why this patch unifies the two fields is to avoid the inconvenience of mutating two
variables at the same time. For example, a log stream replica committer should update the
uncommittedLLSNBegin and local high watermark after committing log entries. Since both are very
similar, we can simplify by merging them.

feat: unify uncommittedLLSNBegin and localHighWatermark in logStreamContext

---

internal/admin/admin.go
internal/admin/init.go

This patch removes verbose logs for grpc_health_probe in the admin server.

chore(admin): remove logs for grpc_health_probe

---

.editorconfig
cmd/rpc_test_server/main.go
pkg/varlog/subscribe.go
proto/mrpb/management.proto
proto/mrpb/metadata_repository.proto
proto/mrpb/raft_entry.proto
proto/mrpb/raft_metadata_repository.proto
proto/snpb/log_io.proto
proto/snpb/log_stream_reporter.proto
proto/snpb/management.proto
proto/snpb/metadata.proto
proto/snpb/replicator.proto
proto/varlogpb/metadata.proto
proto/vmspb/admin.proto

I talked with @hungryjang about the indent size of our project to set it to four spaces rather than
a tab.

style: use four-space indent size for go source files

---

internal/storage/storage.go
internal/storage/storage_test.go

Previously, the log stream wrote a commit context for each commit. However, to
fix #125, we no longer need to persist in a sequence of commit contexts. So
this patch removes lines that keep all commit context.
Updates #125

refactor(storage): do not write a commit context for each commit

---

bin/start_varlogsn.py
cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/storagenode/config.go
internal/storagenode/storagenode.go

This patch deprecates a storage node's `-data-dirs` and `-volume-strict-check` flags. Instead, the
operational script - `start_varlogsn.py` removes data directories not registered to the cluster.
Resolves #215

feat(storagenode): remove bad data dirs and deprecate `--data-dirs` and `--volume-strict-check`

---

pkg/varlog/log.go
pkg/varlog/operations.go
pkg/varlogtest/log.go
pkg/varlogtest/varlogtest_test.go
tests/it/cluster/client_test.go

This patch adds a new API called PeekLogStream to the client. The PeekLogStream returns sequence
numbers at the first and last log entries. Users using LogStreamMetadata or LogStreamReplicaMetadata
to fetch the sequence numbers should use PeekLogStream.
PeekLogStream has the benefits over the ogStreamMetadata or LogStreamReplicaMetadata.
- It does not send users useless and complex information about log stream replicas.
- It prevents users from getting too detailed information about log stream replicas.
- It takes accounts for the status of log stream replicas; thus, it returns more accurate first and last
log sequence numbers of the log stream.
Resolves #239

feat(client): add PeekLogStream to the client

---

internal/benchmark/benchmark.go
internal/benchmark/metrics.go
internal/benchmark/report.go
internal/benchmark/target.go

This patch adds a reporter to the benchmark and prints out metrics while executing the benchmark.
Below are the sample metrics:
```
___tgt__arpsR__arpsT_______abpsR_______abpsT__adurR__adurT__slpsR__slpsT_______sbpsR_______sbpsT__eelatR__eelatT
1:*   77.3   77.3  96.65KiB/s  96.65KiB/s   12.0   12.0    0.0    0.0        0B/s        0B/s     0.0     0.0
1:1   77.7   77.7  97.07KiB/s  97.07KiB/s   12.0   12.0    0.0    0.0        0B/s        0B/s     0.0     0.0
___tgt__arpsR__arpsT_______abpsR_______abpsT__adurR__adurT__slpsR__slpsT_______sbpsR_______sbpsT__eelatR__eelatT
1:*   76.3   76.8  95.42KiB/s  96.04KiB/s   12.0   12.0    0.0    0.0        0B/s        0B/s     0.0     0.0
1:1   77.0   77.3  96.25KiB/s  96.66KiB/s   12.0   12.0    0.0    0.0        0B/s        0B/s     0.0     0.0 …
```

refactor(benchmark): add a reporter to the benchmark

---

cmd/benchmark/benchmark.go

This patch adds a new command `test` to the benchmark tool. It runs benchmark testing that is
already implemented. We will add more commands like save and serve to support various
functionalities.
Resolves #257

feat(benchmark): add a `test` command to the benchmark tool

---

internal/storagenode/storagenode.go

This patch fixed concurrency bugs in the storage setting and executor setting. Issue #262 describes
it concretely.
Resolves #262

fix(storagenode): fix concurrency bugs of settings for storage and executor

---

cmd/benchmark/test_command.go
internal/benchmark/benchmark.go
internal/benchmark/config.go
internal/benchmark/metrics.go
internal/benchmark/report.go
internal/benchmark/report_codec.go
internal/benchmark/target.go

This patch adds a new flag - `--print-json` to the benchmark tool's test command. This flag lets the
benchmark print to its output as JSON.
Updates #257

feat(benchmark): add `--print-json` to print benchmark result as JSON

---

tests/ee/ee_test.go

This patch lets the local e2e test skip the flaky test - TestVarlogEnduranceExample.

test(e2e,local): Skip the flaky test - TestVarlogEnduranceExample

---

tests/ee/cluster/config.go
tests/ee/cluster/local/config.go
tests/ee/cluster/local/daemon/daemon.go
tests/ee/cluster/local/storagenode/config.go
tests/ee/cluster_k8s.go
tests/ee/cluster_local.go
tests/ee/ee_test.go

This patch changes the following things for the local end-to-end test:
- changes logger from normal zap to zaptest
- adds the StorageNodeID tag to the storage node
- terminates storage node by sending SIGINT instead of SIGKILL
- changes the base port of the storage node from 50001 to 20001
Previously the test failed due to a bind error at port 50004. I think changing the storage node's base port is key to resolving this issue.
Resolves #280

test(e2e,local): flaky test TestVarlogEnduranceExample

---

cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/storagenode/client/management_client.go
internal/storagenode/config.go
internal/storagenode/storagenode.go
internal/storagenode/storagenode_test.go

This patch adds a new CLI flag, `--max-logstream-replicas-count,` which limits the number of log
stream replicas in a storage node. The default value is -1, meaning no upper limit, and a storage
node cannot create a log stream replica if it is zero.
A storage node keeps a count variable for the number of log stream replicas. Whenever the storage
node creates a new replica, it checks if the number of log stream replicas exceeds the upper limit.
If there is no problem, the storage node creates a new replica and increases the count variable.
Conversely, the storage node decreases the count variable whenever a log stream replica is removed.
This approach has a limitation: it cannot distinguish between standard and garbage replicas.
Fundamentally, a storage node has no method to distinguish …

feat(storagenode): add an upper limit of log stream replicas count in a storage node

---

internal/admin/admin.go
internal/admin/admin_test.go

Even if metarepos controls UpdateLogStream, admin should also reject UpdateLogStream that do not meet the conditions in order not to create unnecessary replicas. The admin collects the replica status of the requested UpdateLogStream from storageNode and decides whether to perform it.
Resolves #303 

feat(admin): reject UpdateLogStream if there is no sealed Replica

---

internal/admin/mrmanager/manager.go
internal/admin/server.go
pkg/mrc/metadata_repository_client.go
pkg/varlog/admin.go
proto/vmspb/admin.pb.go
proto/vmspb/admin.proto
tests/it/management/management_test.go

The admin server and client respect the error code ResourceExhausted if the log stream count reaches
the upper limit.
Updates #293, #297

feat(admin): return ResourceExhausted if the log streams count overflows

---

internal/admin/mrmanager/manager.go
internal/admin/server.go
pkg/mrc/metadata_repository_client.go
pkg/varlog/admin.go
proto/vmspb/admin.pb.go
proto/vmspb/admin.proto
tests/it/config.go
tests/it/management/management_test.go
tests/it/testenv.go

This patch provides a way to set customized options for the metadata repository and storage nodes in
the integration testing environment. The customized options override the implicit options selected
by the testing environment.

test(it): add customizing options for the MR and SN

---

internal/admin/admin.go
proto/admpb/admin.pb.go
proto/admpb/admin.proto

This patch defines the gRPC error codes of various RPCs in the admin server. Previously, we depended
on the `verrors` package to identify the cause of errors. However, the `verrors` package is vague
and an anti-pattern. To handle errors explicitly, we are trying to adopt gRPC error codes.
Although this PR doesn't convert everything, it can be a starting point for our robust error
handling.
Updates #312

feat(admin): defines error codes of several RPCs in the admin server

---

internal/storagenode/errors/errors.go
internal/storagenode/log_server.go
internal/storagenode/logstream/append.go
internal/storagenode/storagenode_test.go
proto/snpb/log_io.go
proto/snpb/log_io.pb.go
proto/snpb/log_io.proto

This patch adds gRPC error codes to the RPCs of the log server in the storage node. Previously the
storage node had no use of gRPC error codes. Instead, it used the `verrors` package that serializes
and deserializes the error messages into and from strings.
```
+-------------+     +-------------------------+
|             |     |  Client                 |
|             |     |  Library +------------+ |                +------------+
|             |     |          |            | |                |            |
|    User     |   sentinel     |            | |  encode error  |            |
| Application |<----error------+ RPC Client |<+--message into -| RPC Server |
|             |     |          |            | |    Details     |            |
|             |     |          |            | | …
```

feat(storagenode): add gRPC error codes to the log server

---

internal/storagenode/admin_server.go
internal/storagenode/errors/errors.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/executor_test.go
internal/storagenode/storagenode.go
internal/storagenode/storagenode_test.go
proto/snpb/management.pb.go
proto/snpb/management.proto

This patch adds gRPC error codes to the RPCs of the admin service in the storage node.
Updates #312

feat(storagenode): add gRPC error codes to the admin service

---

internal/metarepos/reportcommit_test.go
internal/storagenode/testing.go
proto/snpb/log_stream_reporter.pb.go
proto/snpb/log_stream_reporter.proto

This PR adds a new test, TestReportCommit, to verify RPCs between the metadata repository and
storage node.
Updates #337

test(storagenode,metarepos): verify RPCs between the metadata repository and storage node

---

internal/metarepos/reportcommit_test.go

This patch fixed the flaky test TestReportCommit.
Intermittent failure of this test resulted from a lack of stale version check in the CommitBatch handler of the LogStreamReporterServer mock. This PR added the examination of the old version.

test(metarepos): fix flaky test TestReportCommit

---

internal/metarepos/reportcommit_test.go

It fixes a race problem in `TestReportCommit` caused by #379.
Updates #379

fix(metarepos): fix race in TestReportCommit

---

internal/metarepos/raft_metadata_repository_test.go

It increased the test timeout for TestMRScaleOutJoin to avoid intermittent failures.

test(metarepos): increase test timeout of flaky test TestMRScaleOutJoin

---

internal/storage/recovery_points.go
internal/storage/storage.go

This PR changes that the `internal/storage.(*Storage).ReadCommitContext` uses `ErrNoCommitContext` instead of `pebble.ErrNotFound`. It makes the error more illustrative.

refactor(storage): use ErrNoCommitContext instead of ErrNotFound

---

internal/storagenode/logstream/committer.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/executor_test.go
internal/storagenode/logstream/log_stream_context.go
internal/storagenode/logstream/log_stream_context_test.go
internal/storagenode/logstream/subscribe.go
internal/storagenode/logstream/sync.go

This patch recovers an empty log stream replica which has been trimmed all log entries. Since the
empty log stream replica has no log entries, its local low and high watermarks are invalid. However,
its commit context has evidence to recover its state while restarting.
Soon, we will change the behavior of Trim to be able to remove all log entries from a log stream
replica. This PR prepares it.
Updates #351

feat(storagenode): restore trimmed log stream replica

---

internal/storagenode/logstream/executor_test.go
internal/storagenode/logstream/sync.go
internal/storagenode/logstream/sync_client.go
internal/storagenode/replication_server.go
internal/storagenode/storagenode_test.go
proto/snpb/replicator.go
proto/snpb/replicator.pb.go
proto/snpb/replicator.proto

This patch changes the behavior of SyncInit to handle empty source replicas. Previously SyncInit
thought that an empty source could not exist. Changes are the followings:
- Destination replica, SyncInit RPC server replies gRPC AlreadyExists error if it already has enough
log entries and a commit context.
- Destination replica trims its local log entries if the source replica already did and receives a
commit context if necessary.
Soon, we will change the behavior of Trim to be able to remove all log entries from a log stream
replica. This PR prepares it.
Updates #351

feat(storagenode): change SyncInit to handle trimmed source replica

---

internal/reportcommitter/testing.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/executor_test.go
internal/storagenode/logstream/subscribe.go
internal/storagenode/storagenode_test.go
vendor/golang.org/x/exp/maps/maps.go
vendor/modules.txt

This patch changes the Trim API of the log stream. Previously, the Trim API does not remove all logs
because of some historical reason (#351). However, it has no reason to do that anymore.
This PR also contains some changes for Subscribe API to handle trimmed log streams.
Resolves #351
Varlog's Trim API has some limitations.
Trim API removes prefix log entries of only log stream replica in the APPENDABLE status, and I will
fix it soon.
In addition, the log stream can't know the global low watermark after a restart because it keeps it
in memory. Therefore, Subscribe API can't decide whether it returns an empty result or error
indicating that the log entries are already trimmed, and it needs some discussion for a design
decision.

feat(storagenode): trim API with no safety gap

---

internal/storage/logger.go

This patch fixed the storage log that was printed abnormally, for instance, `%!(EXTRA []interface {}=[])`.

fix(storage): prints storage log clearly

---

bin/start_varlogsn.py
cmd/varlogsn/cli.go
internal/storagenode/config.go

This patch fixed operation scripts `start_varlogsn.py` to configure ballast size.

fix(storagenode): configure ballast by using flags

---

cmd/varlogsn/varlogsn.go

This PR adds [automaxprocs](go.uber.org/automaxprocs) to the storage node, which is already used by
admin or metadata repository. It configures GOMAXPROCS automatically.

feat(storagenode): add automaxprocs to storagenode

---

bin/start_varlogsn.py
cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/storage/config.go
internal/storage/storage.go

This patch changes logging for storage:
- Make event logging less verbose, which enables only logs for errors and slow I/O.
- Add metrics logging to the storage for investigating details.

feat(storage): metrics logging and less verbose event logging

---

internal/storagenode/executorsmap/executors_map_test.go

Do not use deprecated global rand seed.
See:
- https://github.com/golang/go/issues/54880

refactor(storagenode): do not use deprecated global rand seed

---

cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go

This PR fixed setting the flag `--storage-mem-table-size` correctly in the storage node.

fix(storagenode): set the flag --storage-mem-table-size correctly

---

internal/admin/replica_selector.go
internal/admin/replica_selector_mock.go

It adds a new method `Name() string` to the replica selector interface
`internal/admin.(ReplicaSelector)`. We can set a unique name for each replica selector, and
therefore, we can use a necessary replica selection algorithm by specifying the name.
Updates #393

feat(admin): add a name to the replica selector

---

go.mod
internal/admin/config.go
internal/admin/replica_selector.go
internal/admin/replica_selector_test.go

This PR adds a new replica selector based on the Least Frequently Used (LFU) algorithm.
`lfuReplicaSelector` selects each replica's storage node and data path, giving preference to those
with fewer assigned replicas.
All replica selectors, including `lfuReplicaSelector`, are stateless, meaning they don't keep
existing log stream topology. When `Select` is invoked, `lfuReplicaSelector` collects used counters
for each storage node and path. Although it seems to be inefficient, it is simple as well as
fault-tolerant.
To select the least used storage nodes and paths, `lfuReplicaSelector` runs as follows:
- Fetch cluster metadata from the `ClusterMetadataView`.
- Increase the used counters for each storage node and path assigned to each log stream.
- Sort counters.
- Choose the least used …

feat(admin): LFU replica selector

---

cmd/varlogadm/cli.go
cmd/varlogadm/flags.go
internal/admin/admin.go
internal/admin/config.go
internal/admin/replica_selector.go
internal/admin/replica_selector_test.go

It added a new flag, `replica-selector`, to the varlogadm. The flag sets the global default replica
selector.
Updates #393

feat(admin): add a new flag `replica-selector` to the varlogadm

---

Makefile

Recently time taking running unit tests has become longer. In addition, some flaky tests are failed
on low-performance systems. This PR increases test timeout from 10m to 20m and reduces parallelism
by specifying "-p 1".

ci(make): increase test timeout and reduce parallelism

---

bin/start_varlogsn.py
cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/storage/append_batch.go
internal/storage/benchmark_test.go
internal/storage/config.go
internal/storage/recovery_points.go
internal/storage/scanner.go
internal/storage/storage.go
internal/storage/storage_test.go
internal/storage/testing.go
internal/storagenode/logstream/executor_test.go
internal/storagenode/storagenode.go
internal/storagenode/volume/volume.go

This PR implemented the idea of separating the storage database, which was proposed by @hungryjang.
It divides storage databases into two parts: data database and commit database. The data part
stores records whose keys are LLSNs and whose values are log data users append. The commit part
stores records whose keys are GLSNs and whose values are LLSNs.
This approach is very performant compared to the previous one. Especially the data part can take
advantage of move compaction dramatically. Empirically throughput can be increased by about 10-20%
and append duration reduced by about 10-20%.
However, it doubles the number of pebble instances. We should configure the storage databases
carefully to overcome this.

feat(storage): separate storage databases experimentally

---

internal/storagenode/logstream/append.go
internal/storagenode/logstream/replicate_task.go
internal/storagenode/logstream/sequencer.go
internal/storagenode/logstream/sequencer_test.go

The `replicateTaskSlicePool` pooled slices of `replicateTask`. The function
`releaseReplicateTaskSlice` received borrowed slice and then put it into `replicateTaskSlicePool`.
However, the `sync.(Pool).Put` parameter is an interface, so the slice escaped to the heap
unnecessarily.
Not to use unnecessary heap objects, this PR wraps the `replicateTask` slice with the struct
replicateTaskSlice. 
Resolves #75

perf(storagenode): wrap replicateTask slice with struct

---

internal/storagenode/logstream/committer.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/replicate_client.go
internal/storagenode/logstream/sequencer.go
internal/storagenode/logstream/sync.go
internal/storagenode/logstream/writer.go

This PR slightly improves the storage node's performance by checking the log level, making the
logger not make slices in advance.

perf(storagenode): check log level

---

internal/storagenode/logstream/append.go

This PR estimates the number of batchlets more accurately. Previously, the number of batchlets is
estimated by dividing the size of batches by the smallest batchlet. It is now divided by the right
size of batchlet.

perf(storagenode): estimate the number of batchlets

---

cmd/varlogsn/varlogsn.go
internal/metarepos/raft.go
internal/metarepos/raft_metadata_repository.go
internal/metarepos/report_collector.go

Because the metadata repository sets node id as resource `service.instance.id`, it does not need to
use a redundant label - `nodeid`.
Resolve #423

chore(metarepos): do not use unnecessary labels

---

internal/metarepos/report_collector.go
proto/mrpb/raft_metadata_repository.go

This patch adds an `mrpb.StorageNodeUncommitReport` pool, which is
`proto/mrpb.storageNodeUncommitReportPool`. It reduces heap objects allocated repeatedly whenever
processing reports received from storage nodes.
Below heap profiling is the previous result.
```
flat  flat%   sum%        cum   cum%
70865580  8.38% 44.73%   71293773  8.43%  github.com/kakao/varlog/internal/metarepos.(*reportCollectExecutor).processReport
```
Now here it is after applying this patch.
```
flat  flat%   sum%        cum   cum%
20734504  2.10% 75.92%   42122814  4.26%  github.com/kakao/varlog/internal/metarepos.(*reportCollectExecutor).processReport
```

perf(metarepos): add mrpb.StorageNodeUncommitReport pool

---

cmd/varlogadm/cli.go
cmd/varlogadm/flags.go
cmd/varlogmr/flags.go
cmd/varlogmr/metadata_repository.go
cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/flags/logger.go
internal/metarepos/config.go

This PR adds common flags for logging to package `internal/flags`. Those flags include the
followings:
- `--logdir`
- `--logtostderr`
- `--logfile-max-backups`
- `--logfile-retention-days`
- `--logfile-max-size-mb`
- `--logfile-name-utc`
- `--logfile-compression`
- `--log-human-readable`
- `--loglevel`
Those are very common. Hence all daemons can use them.
Resolves #439

feat(all): add flags for logger

---

internal/metarepos/raft_metadata_repository.go
internal/metarepos/raft_metadata_repository_test.go
internal/metarepos/storage.go
internal/metarepos/storage_test.go
internal/storagenode/logstream/append.go
internal/storagenode/logstream/backup_writer.go
internal/storagenode/logstream/backup_writer_test.go
internal/storagenode/logstream/committer.go
internal/storagenode/logstream/committer_test.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/replicate_client.go
internal/storagenode/logstream/replicate_client_test.go
internal/storagenode/logstream/sequencer.go
internal/storagenode/logstream/sequencer_test.go
internal/storagenode/logstream/subscribe.go
internal/storagenode/logstream/sync.go
internal/storagenode/logstream/writer.go
internal/storagenode/logstream/writer_test.go
internal/storagenode/replication_server.go
internal/storagenode/telemetry/metrics.go
pkg/mrc/mrconnector/mrc_proxy.go
pkg/types/types.go
pkg/types/types_test.go
pkg/util/runner/runner.go
tests/it/cluster/client_test.go

Use new atomic types instead of old atomic functions to avoid misuse of variables.

refactor(all): use atomic types

---

internal/storagenode/logstream/append.go
internal/storagenode/storagenode_test.go

The Append RPC function allows batch logging but may occasionally only partially succeed. The
storage node previously overlooked partial success, but this PR fixes to consider partial success.

fix(storagenode): support partial success/failure for append

---

bin/start_varlogsn.py
cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/storagenode/config.go
internal/storagenode/storagenode.go

This PR adds new gRPC initial flow control window size options to the storage node.
- `--server-initial-conn-window-size`
- `--server-initial-stream-window-size`
See:
- https://httpwg.org/specs/rfc7540.html#InitialWindowSize
- https://pkg.go.dev/google.golang.org/grpc#InitialConnWindowSize

feat(storagenode): add configurations for initial window size

---

internal/storagenode/client/log_client.go
pkg/varlog/config.go
pkg/varlog/errors.go
pkg/varlog/log.go
pkg/varlog/log_mock.go
pkg/varlog/log_stream_appender.go
pkg/varlog/log_stream_appender_test.go
pkg/varlogtest/log.go
pkg/varlogtest/varlogtest_test.go
tests/it/cluster/client_test.go

This PR adds LogStreamAppender to the client, and it is a client to append asynchronously only a particular log stream.
Resolves #433

feat(client): add LogStreamAppender

---

cmd/benchmark/test_command.go
internal/benchmark/loader.go
internal/benchmark/target.go

This PR adds the `--pipeline-size` flag to the benchmark tool. It makes the benchmark test client use LogStreamAppender, which allows pipelined append requests.
- No pipelined requests if the flag is zero (default value).
- Use pipelined requests by using LogStreamAppender if the flag is greater than zero.
The benchmark tool cannot support per-target level pipelined yet. Thus, if the `--pipeline-size` is greater than zero, all the log stream-specific targets will use LogStreamAppender.

test(benchmark): support log stream appender

---

pkg/varlog/config.go
pkg/varlog/log_stream_appender.go
tests/it/cluster/client_test.go

This PR makes `kg/var log.(LogStream Appender).Append Batch` goroutine-safe.

feat(client): support goroutine-safety of pkg/var log.(LogStream Appender).Append Batch

---

pkg/varlog/config.go
pkg/varlog/errors.go
pkg/varlog/log_stream_appender.go
tests/it/cluster/client_test.go

This PR adds a call timeout to the log stream appender. It helps the log stream appender not to be
blocked. LogStreamAppender can be blocked at the following points:
- (a) Waiting for the pipeline to have room
- (b) Flow-controlled when calling RPC
- (c) Stucked server
- (d) Slow callback
```
+------+            +-------------------------+            +--------+
|      |            |    LogStreamAppender    |            |        |
|      |            |                         |            |        |
|      |            |  (a)----------------(b) |            |        |
|      +--AppendBatch--->| pipeline queue |--gRPC request->|        |
| User |            |    +----------------+   |            |        |
| code |            |                         |            | Varlog |
|      | …
```

feat(client): add call timeout to log stream appender

---

pkg/varlog/log.go
pkg/varlog/x/mlsa/manager.go
pkg/varlogtest/log.go
pkg/varlogtest/varlogtest_test.go
tests/it/cluster/client_test.go

This PR adds a manager for log stream appenders, `pkg/varlog/x/mlsa.(Manager)`. It provides two methods:
- `pkg/varlog/x/mlsa.(Manager).Get`: Get a LogStreamAppender specified by the given topic and log stream.
- `pkg/varlog/x/mlsa.(Manager).Any`: Get a writable LogStreamAppender belonging to the given topic.

feat(client): log stream appender manager

---

internal/varlogcli/append.go
pkg/varlog/options.go

Previously, the client provided WithGRPCDialOptions to configure general gRPC client options. However, it was challenging to use since there are so many options in gRPC, and hard for users to know the necessary things.
This PR provides more specific options:
- WithGRPCReadBufferSize
- WithGRPCWriteBufferSize
- WithGRPCInitialConnWindowSize
- WithGRPCInitialWindowSize
It also sets up some options like MaxCallRecvMsgSize and MaxCallSendMsgSize. It uses math.MaxInt32 value for them. Varlog users are not necessarily taken into account the maximum message size limit.

feat(client): add settings for gRPC client

---

internal/storagenode/logstream/executor_test.go
internal/storagenode/logstream/sync.go
internal/storagenode/logstream/testing.go
internal/storagenode/replication_server.go
internal/storagenode/storagenode_test.go

Storage nodes can be trimmed and synchronized. However, there is some bug in that a new destination
replica joined into the log stream rejects SyncInit RPC sent from the trimmed source replica. Those
replicas are all empty and have no log entries; however, the source replica has a commit context
indicating the last committed LLSN. In this situation, the destination replica must accept SyncInit
to receive the commit context from the source replica, but it does not.
This PR fixes the above issue. To solve the problem, it changes the condition that the destination
replica decides whether they are already synchronized.
```go
// Previous code: https://github.com/kakao/varlog/blob/5269481c0e80c2eebf8214116a2d1544a26cb443/internal/storagenode/logstream/sync.go#L297-L302
//
// NOTE: When the …
```

fix(storagenode): accept SyncInit sent from trimmed source to new destination

---

internal/metarepos/raft_metadata_repository.go

Remove the redundant metric, which is `mr.build_commit_results.duration`.

refactor(metarepos): remove redundant metric mr.build_commit_results.duration

---

internal/admin/admin.go
pkg/rpc/interceptors/context.go
pkg/rpc/interceptors/context_test.go
pkg/rpc/interceptors/logging/interceptor.go
pkg/rpc/interceptors/otelgrpc/interceptor.go

This change adds a new gRPC interceptor, pkg/rpc/interceptors/otelgrpc. Currently, it only supports UnaryServerInterceptor. It follows [OTel 1.22.0 specification](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/rpc-metrics/) except for the unit of rpc.server.duration, which converts from milliseconds to microseconds for high resolution.

feat(admin): add otelgrpc metric interceptor

---

internal/metarepos/raft.go
internal/metarepos/raft_metadata_repository.go
internal/metarepos/raft_test.go

This change removes copy overhead caused by unnecessary type casting from byte slice to string. Refer to [this blog](https://www.sobyte.net/post/2022-09/string-byte-convertion/#performance-testing) for performance.

perf(metarepos): avoid copy overhead by removing unnecessary converting from byte slice to string

---

internal/metarepos/raft_metadata_repository.go
proto/mrpb/raft_entry.go

This change adds the pool for mrpb.Reports, which makes the metadata repository reuse heap object for it.

perf(metarepos): add a pool for mrpb.Reports

---

internal/metarepos/raft_metadata_repository.go
proto/mrpb/raft_entry.go
proto/mrpb/raft_entry_test.go

This change adds the pool for []*mrpb.Report, which is reportQueuePool.
```
BenchmarkReportQueuePool/WithoutPool-16                   763526              1573 ns/op            8192 B/op          1 allocs/op
BenchmarkReportQueuePool/WithoutPool-16                   745612              1574 ns/op            8192 B/op          1 allocs/op
BenchmarkReportQueuePool/WithoutPool-16                   738848              1569 ns/op            8192 B/op          1 allocs/op
BenchmarkReportQueuePool/WithoutPool-16                   765339              1563 ns/op            8192 B/op          1 allocs/op
BenchmarkReportQueuePool/WithoutPool-16                   739354              1567 ns/op            8192 B/op          1 allocs/op
BenchmarkReportQueuePool/WithPool-16                     4445330 …
```

perf(metarepos): add a pool for []*mrpb.Report

---

internal/metarepos/raft_metadata_repository.go
proto/mrpb/raft_entry.go

This change adds the pool for *mrpb.RaftEntry to reuse it.

perf(metarepos): add a pool for *mrpb.RaftEntry

---

internal/metarepos/report_collector.go
internal/metarepos/report_collector_test.go

This change makes mrpb.StorageNodeUncommitReport is reused when it is replaced with a new one.
Previous PR, #446, introduced a pool for mrpb.StorageNodeUncommitReport. However, the old
StorageNodeUncommitReport stored to reportContext was not reused, and this PR improves it.
To release the StorageNodeUncommitReport registered to reportContext, some methods of reportContext
are changed:
- (*reportContext).getReport returns a value of StorageNodeUncommitReport rather than a pointer. It
makes releasing the StorageNodeUncommitReport happen at any time.
- add (*reportContext).swapReport to set a new StorageNodeUncommitReport and get the old one
simultaneously.
- getReport and swapReport return the boolean result to indicate whether the result report is zero
value.
BenchmarkSwapReport evaluates …

perf(metarepos): reuse mrpb.StorageNodeUncommitReport while changed

---

internal/metarepos/report_collector.go
internal/metarepos/report_collector_test.go
proto/mrpb/raft_metadata_repository.go

Fix typo from NewStoragenodeUncommitReport to NewStorageNodeUncommitReport.

chore(metarepos): fix typo from NewStoragenodeUncommitReport to NewStorageNodeUncommitReport

---

cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/storage/config.go
internal/storage/storage.go

This change adds a new flag --storage-trim-delay to the storage node. It sets the delay before storage removes logs. If the value is zero, Trim will delay the removal of prefix log entries until writing additional log entries.

feat(storagenode): add --storage-trim-delay to set a delay before the deletion of log entries

---

cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/storage/config.go
internal/storage/storage.go

This change adds a new flat --storage-trim-rate to the storage node. It sets the deletion throttling rate for Trim operation. If the value is zero, Trim removes the log entries without throttling.

feat(storagenode): add --storage-trim-rate to set throttling rate of Trim

---

internal/benchmark/report_codec.go
pkg/util/units/units.go
pkg/util/units/units_test.go

Before:
```
___tgt__arpsR__arpsT_______abpsR_______abpsT__adurR__adurT__slpsR__slpsT_______sbpsR_______sbpsT__eelatR__eelatT
1:123664.023244.1  92.44MiB/s   90.8MiB/s    4.0    4.0    0.0    0.0        0B/s        0B/s     0.0     0.0
```
Current:
```
target_____arps(now,tot)_________abps(now,tot)_adur(now,tot)_____slps(now,tot)_________sbps(now,tot)__eelat(now,tot)
1:1  24.3k/s 23.38k/s 94.93MiB/s 91.32MiB/s  4.4ms  4.6ms      0/s      0/s       0B/s       0B/s   0.0ms   0.0ms
```

chore(benchmark): improve the readability of benchmark stats

---

cmd/benchmark/test_command.go
internal/benchmark/benchmark.go
internal/benchmark/config.go
internal/benchmark/loader.go

This change adds a new flag, `--single-conn-per-target`, which makes appenders in a benchmark target share a connection.

feat(benchmark): share a connection between appenders in a target

---

internal/benchmark/benchmark.go
internal/benchmark/loader.go

This change makes the benchmark loader stop gracefully. Previously the benchmark loader stopped regardless of inflight requests. In terms of performance testing, it is not important though it is not intended. From now, the benchmark tool will stop its performance testing gracefully; that is, it won't terminate ongoing requests.

fix(benchmark): support graceful stop

---

internal/admin/mrmanager/manager.go

This PR improves `internal/admin/mrmanager.(*mrManager).ClusterMetadata` performance:
- Fail-fast: If the given context is canceled, it returns a context error without acquiring the mutex.
- Fast-path: If the cluster metadata does not need to update, it returns the existing thing without the exclusive lock.
- Slow-path: It is similar to the previous implementation but shares the updated cluster metadata using a singleflight.
This PR makes the `internal/admin/mrmanager.(*mrManager).ClusterMetadata` more concurrent and removes unnecessary RPCs. It also avoids RPC calls within exclusive mutex.

feat(admin): speed up fetching cluster metadata

---

internal/admin/mrmanager/manager.go

This PR makes the mrmanager avoid unnecessary fetching cluster metadata by checking the dirty field only when the MR is mutated successfully.

refactor(admin): set dirty field only when the MR is mutated

---

internal/storage/recovery_points.go
internal/storage/testing.go
internal/storagenode/logstream/committer.go
internal/storagenode/logstream/committer_test.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/executor_test.go
internal/storagenode/logstream/sequencer.go

Currently, all log stream replicas belonging to the storage nodes that are just
restarted can't commit logs written before restarting if all log stream
replicas in a log stream were restarted simultaneously. They have logs
uncommitted in their storages, but they can't process Commit RPC sent from the
metadata repository.
This PR fixes the above issue. While recovering the log stream context after
restarting the storage nodes, it restores uncommitted logs.
Resolves #490

fix(storagenode): restore uncommitted logs

---

internal/admin/admin.go
internal/admin/sfgkey/keys.go

This PR makes the admin server handle RPCs by using singleflight. It helps the admin to reduce redundant computation, especially read operations.
I am only altering read operations. However, it is possible to refactor the admin server to eliminate the use of a single big lock.

perf(admin): use singleflight to handle Admin's RPCs

---

internal/storagenode/logstream/append.go
internal/storagenode/logstream/append_waitgroup.go

Append batch requests can succeed partially. In case of partial failure, failed log entries must be sequential. That is, suffixes of the batch can be failed to append, whose length can be from zero to the full size.
Our codebase panics when the batch's success and failure are interleaved. This PR ignores context errors caused by clients since the batch can succeed in the storage node, although clients canceled it.

fix(storagenode): ignore context error while checking to interleave of Append RPC errors

---

pkg/varlog/x/mlsa/manager.go
tests/it/cluster/client_test.go

This change adds a new method, Clear to the log stream appender manager. Clear closes all the log stream appenders registered to the Manager and removes them. It does not destroy the Manager. Therefore, users can continue using it after calling Clear. However, users have to call Clear after completing the use of the Manager to release associated resources.

feat(client): add Clear to the log stream appender manager

---

internal/admin/admin.go
internal/admin/testing.go
internal/metarepos/raft_metadata_repository.go
internal/storagenode/logstream/testing.go
internal/storagenode/storagenode.go
internal/storagenode/testing.go
pkg/rpc/manager_test.go
pkg/rpc/server.go
pkg/util/testutil/conveyutil/conveyutil.go

This PR provides a new function to create a gRPC server. It helps the gRPC server use gogoproto
codec.
Update #235.

feat(all): add gogoproto codec to grpc servers

---

cmd/varlogadm/cli.go
cmd/varlogadm/flags.go
cmd/varlogmr/flags.go
cmd/varlogmr/metadata_repository.go
internal/admin/admin.go
internal/admin/config.go
internal/flags/cluster.go
internal/flags/flags_test.go
internal/metarepos/config.go
tests/ee/cluster/local/metarepos/node.go
tests/it/testenv.go

Previously varlogadm and varlogmr defined the flag for replication factor, respectively, which made strings for the flag different.
This change adds a new standard flag, `--replication-factor`. It also sets the type of replication factor to an integer.

refactor: add the standard flag --replication-factor

---

pkg/varlogtest/config.go
pkg/varlogtest/varlogtest.go
pkg/varlogtest/varlogtest_test.go

This PR adds functional options to the varlogtest.

feat(varlogtest): add functional options to varlogtest

---

pkg/varlogtest/admin.go
pkg/varlogtest/config.go
pkg/varlogtest/varlogtest.go
pkg/varlogtest/varlogtest_test.go

This PR adds an option to set initial metadata repository nodes and supports fetch APIs for the metadata repository nodes in the varlogtest admin. Although it doesn't provide mutation APIs for the metadata repository yet, it will be helpful to test the varlog.

feat(varlogtest): add initial metadata repository and support fetch APIs

---

pkg/varlogtest/admin.go
pkg/varlogtest/log.go
pkg/varlogtest/varlogtest.go
pkg/varlogtest/varlogtest_test.go

This PR renames `pkg/varlogtest.(*VarlogTest).Admin` and `pkg/varlogtest.(*VarlogTest).Log` to `pkg/varlogtest.(*VarlogTest).NewAdminClient` and `pkg/varlogtest.(*VarlogTest).NewLogClient` respectively. It also makes them return a new instance of the admin client and the log client when invoked.
Previously, they returned the same instances, so callers shared them. However, it wasn't the right decision because the callers had to share the clients regardless of their needs.

feat(varlogtest): create new instance of admin and log

---

pkg/varlogtest/log.go
pkg/varlogtest/varlogtest_test.go

This PR fixed the log stream appender's bug in the varlogtest package. It had
the bug that the callback in the log stream appender didn't return an error.

fix(varlogtest): log stream appender returns missing errors in the callback

---

pkg/varlogtest/log.go
pkg/varlogtest/varlogtest.go
pkg/varlogtest/varlogtest_test.go

This PR fixed the varlogtest to be able to close the log stream appender in the callback.

fix(varlogtest): log stream appender can be closed in the callback

---

internal/admin/mrmanager/manager.go

This PR changes the role of `internal/admin/mrmanager.(*mrManager).mu`. The large lock in the mrmanager made the mrmanager run sequentially. However, from now, it only guards the dirty flag for the cluster metadata. Since the metadata repository works concurrently, adopting a large lock on the client side is unnecessary.

refactor(admin): prevent the large lock from mrmanager

---

internal/admin/mrmanager/manager.go
tests/it/testenv.go

This PR adds codes to check cluster id in mrmanager. Because the admin server doesn't have explicit health checking, comparing cluster id is performed in ClusterMetadataViewer.
In the next PR, checking the replication factor will be added.

feat(admin): check cluster id in mrmanager

---

cmd/varlogadm/cli.go
internal/admin/mrmanager/config.go
internal/admin/mrmanager/manager.go
tests/it/testenv.go

This PR adds codes to check the replication factor in mrmanager. It compares the replication factors configured in the admin and metadata repository.

feat(admin): check replication factor in mrmanager

---

internal/admin/admin.go

This PR prevents the large lock from `internal/admin.(*Admin)`. Concretely it changes the role of  `internal/admin.(*Admin).mu` from the single huge lock to guarding the fields such as `lis`, `serverAddr`, and `closed`.

refactor(admin): prevent large lock from internal/admin.(*Admin)

---

pkg/varlogtest/admin.go
pkg/varlogtest/varlogtest_test.go

This PR implements ListLogStreams for the varlogtest package.

feat(varlogtest): support ListLogStreams API

---

tests/ee/cluster/local/cluster.go

This PR fixed the e2e test to run the correct number of MR nodes.

fix(e2e): run the correct number of MR nodes

---

bin/start_varlogsn.py

This PR fixed the JSON parsing of the get_data_dirs function in the start_varlogsn.py script. It has been affected by #606.

fix(varlogsn): fix JSON parsing of get_data_dirs in start_varlogsn

---

internal/storage/recovery_points.go
internal/storage/storage_test.go

Previously the method `internal/(*storage).ReadRecoveryPoints` returned an error when it found an inconsistency between data and commit for log entries, which could happen when there was no data for a commit. It should not have happened when we used the unified database in storage, so the method returned an error.
However, using separate databases in storage and turning off the WAL sync option can happen; for instance, the data for a log entry can be lost, although the commit for that log entry is synced.
This PR makes the ReadRecoveryPoints not return an error for the inconsistency between data and commit for a log entry. It tries to find the first and last log entries that have no inconsistency. If there are no valid first and last, it returns nil for them and lets them be resolved …

feat(storage): handle inconsistency between data and commit in ReadRecoveryPoints

---

pkg/varlogtest/varlogtest.go
pkg/varlogtest/varlogtest_test.go

Package varlogtest could panic when a user calls PeekLogStream after deleting
all logs from a log stream. This PR fixed the bug.

fix(varlogtest): panic on PeekLogStream after removing all logs

---

proto/mrpb/management.pb.go
proto/mrpb/management.proto

This PR adds specifications to "proto/mrpb/management.proto". This helps us
establish agreements for the contracts of the metadata repository's management
RPCs.
Update: #658

docs(metarepos): add specification to management RPCs

---

pkg/varlog/subscribe.go

This PR removes the initial delay from the client's Subscribe API. It now
refreshes subscribers manually to fetch logs immediately.

fix(client): remove subscribe's initial delay

---

.github/workflows/ci.yaml
Makefile
go.mod

Use Go 1.22 and golangci-lint 1.56.2.

ci: use Go 1.22

---

internal/storage/benchmark_test.go

This PR introduces a new benchmark, BenchmarkStorage_ScanWithGLSN, to measure
storage performance when scanning with GLSN across various scan sizes. The
benchmark will serve as foundational data for performance optimization efforts.
Changes:
- Implemented the BenchmarkStorage_ScanWithGLSN benchmark
- Added logic to measure performance across different scan sizes
- Laid groundwork for recording and analyzing performance measurement results

test(storage): add benchmark for scanning with GLSN

---

Makefile
internal/admin/mrmanager/manager_mock.go
internal/admin/replica_selector_mock.go
internal/admin/snmanager/manager_mock.go
internal/admin/snwatcher/snwatcher_mock.go
internal/admin/stats/repository_mock.go
internal/reportcommitter/client_mock.go
internal/storagenode/client/management_client_mock.go
pkg/mrc/metadata_repository_client_mock.go
pkg/mrc/metadata_repository_management_client_mock.go
pkg/varlog/admin_mock.go
pkg/varlog/log_mock.go
pkg/varlog/log_stream_appender_mock.go
pkg/varlog/metadata_refresher_mock.go
pkg/varlog/replicas_retriever_mock.go
proto/admpb/admin_mock.go
proto/mrpb/mock/mrpb_mock.go
proto/snpb/mock/snpb_mock.go

Bump go.uber.org/mock/mockgen from v0.3.0 to v0.4.0.

ci: bump go.uber.org/mock/mockgen from v0.3.0 to v0.4.0

---

go.mod

Use 1.22.0 in go.mod.
See: <https://github.com/github/codeql/issues/15647#issuecomment-1949920878>

chore(go): use 1.22.0 in go.mod

---

internal/benchmark/loader.go
pkg/varlog/options.go
vendor/google.golang.org/grpc/experimental/experimental.go
vendor/modules.txt

When a client library parses incoming gRPC messages, it allocates new buffers
frequently. This can result in the creation of a large number of heap objects.
However, gRPC offers an experimental feature called the shared buffer pool that
can be used to address this issue.
This pull request (PR) aims to optimize the gRPC receiving path using the shared
buffer pool. Various experiments have shown that this optimization leads to a
decrease in CPU time of runtime.gcBgMarkWorkers, depending on the workload.
Since the shared buffer pool is experimental, it is applied only to the
benchmark.
Refs:
- <https://pkg.go.dev/google.golang.org/grpc@v1.62.0/experimental#WithRecvBufferPool>
- <https://pkg.go.dev/google.golang.org/grpc@v1.62.0#SharedBufferPool>

perf(benchmark): use grpc.SharedBufferPool for grpc.DialOption

---

internal/storagenode/client/log_client.go
internal/storagenode/client/log_client_test.go

This pull request optimizes
`internal/storagenode/client.(*LogClient).Subscribe`. It reuses
`snpb.SubscribeResponse` to reduce heap allocations. Note that it does not reuse
the byte slice in the `snpb.SubscribeResponse`. It only reuses the struct
`snpb.SubscribeResponse` itself.

perf(client): reuse snpb.SubscribeResponse in RPC handler

---

pkg/varlog/subscribe.go

Switches the type of `pkg/varlog.(subscriber).lastSubscribeAt` from
`atomic.Value` to `atomic.Int64` to eliminate heap escapes. The frequent updates
with new `time.Time` values to `lastSubscribeAt` previously led to significant
heap allocation due to heap escape. By adopting `atomic.Int64`, we can prevent
heap escape, thereby reducing heap allocations and enhancing performance.

perf(client): optimize with atomic.Int64 for lastSubscribeAt in pkg/varlog.(subscriber)

---

bench_tq.sh
pkg/varlog/benchmark_test.go
pkg/varlog/subscribe.go

This PR preallocates `pkg/varlog.(*transmitter).transmitQueue`.
Benchmark:
```
goos: darwin
goarch: amd64
pkg: github.com/kakao/varlog/pkg/varlog
cpu: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
│ out.NoAlloc │            out.PreAlloc             │
│   sec/op    │   sec/op     vs base                │
TransmitQueue/128-8    17.88µ ± 1%   16.57µ ± 0%   -7.34% (p=0.000 n=20)
TransmitQueue/1024-8   149.7µ ± 0%   136.3µ ± 0%   -8.93% (p=0.000 n=20)
TransmitQueue/8192-8   1.313m ± 1%   1.156m ± 0%  -11.97% (p=0.000 n=20)
geomean                152.0µ        137.7µ        -9.43%
│  out.NoAlloc  │             out.PreAlloc             │
│     B/op      │     B/op      vs base                │
TransmitQueue/128-8     14.40Ki ± 0%   12.29Ki ± 0%  -14.65% (p=0.000 n=20)
TransmitQueue/1024-8   138.40Ki …
```

perf(client): prealloc pkg/varlog.(*transmitter).transmitQueue

---

cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/storage/cache.go
internal/storage/config.go
internal/storage/storage.go
internal/storage/storage_test.go
internal/storage/testing.go

This pull request adds a cache to shared storage across all storage, which is
set by the CLI flag '--storage-cache-size. Internally, it is a block cache of
Pebble that stores data in the Varlog. The cache's default size is 128
megabytes.

feat(storage): add cache to storage

---

internal/storagenode/client/manager_test.go
pkg/rpc/manager_test.go
pkg/rpc/rpc_conn.go
tests/it/mrconnector/mr_connector_test.go

Replace grpc.DialContext with grpc.NewClient in the rpc package to align with
updated gRPC practices. The NewClient method creates a gRPC channel without
performing I/O operations immediately, improving the connection management
logic.
- Update NewConn to use grpc.NewClient instead of grpc.DialContext.
- Add detailed comments to explain the behavior of NewClient.
- Modify TestManager to ensure each test case has an independent Manager
instance.
- Adjust UnreachableServer test case to reflect non-blocking behavior of
NewClient.
This change ensures better resource management and aligns with the latest gRPC
client connection practices.
See:
- <https://pkg.go.dev/google.golang.org/grpc#NewClient>
- <https://pkg.go.dev/google.golang.org/grpc#DialContext>

fix(rpc): use google.golang.org/grpc.NewClient instead of DialContext

---

.github/workflows/ci.yaml
.golangci.yaml
Makefile
cmd/benchmark/serve_command.go
internal/benchmark/loader.go

Bump golangci-lint from v1.56 to v1.59.

ci(lint): bump golangci-lint from v1.56 to v1.59

---

build/Dockerfile

This pull request updates github.com/grpc-ecosystem/grpc-health-probe from
v0.4.11 to v0.4.26.

chore(dockerfile): bump grpc health probe from v0.4.11 to v0.4.26

---

internal/storagenode/log_server.go
internal/storagenode/logstream/append.go
internal/storagenode/telemetry/metrics.go

This pull request defines metrics for measuring RPCs such as Append and
Replicate. It introduces four metrics:
- `log_rpc.server.duration` measures the time spent processing inbound RPC calls
in microseconds. It is very similar to the `rpc.server.duration` defined by
OpenTelemetry, but our metric also measures the processing time triggered by
each call on a gRPC stream.
- `log_rpc.server.log_entry.size` measures the size of appended log entries. It
is similar to the `rpc.server.request.size` metric, but our metric measures
the size of each log entry included in the appended batch.
- `log_rpc.server.batch.size` measures the size of log entry batches appended.
- `log_rpc.server.log_entries_per_batch` measures the number of log entries per
appended batch.
These metrics are histogram-type, …

feat(sn): add metrics for Append and Replicate RPCs

---

build/Dockerfile

This pull request adds [jq](https://jqlang.github.io/jq/) to Docker containers.
It helps users easily process results from varlogctl.

build(docker): add jq for processing results from varlogctl

---

internal/storagenode/replication_server.go

Ensure the replication server
(github.com/kakao/varlog/internal/storagenode.(*replicationServer)) handles
closed request channels properly, preventing a panic caused by nil dereference.
This will prevent flaky test failures
(https://github.com/kakao/varlog/actions/runs/9547361613/job/26312306907) such
as:
```
2024/06/17 12:13:12 SN.Close: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14d171e]
goroutine 35903 [running]:
github.com/kakao/varlog/internal/storagenode.(*replicationServer).replicate.func1()
/home/runner/work/varlog/varlog/internal/storagenode/replication_server.go:154 +0x21e
created by github.com/kakao/varlog/internal/storagenode.(*replicationServer).replicate in goroutine 35936 …
```

fix(sn): prevent panic on closed queue channel of replication server

---

internal/metarepos/raft_metadata_repository_test.go
internal/metarepos/raft_test.go
internal/metarepos/report_collector_test.go
internal/metarepos/storage_test.go
internal/vtesting/init.go
pkg/mrc/mrconnector/mr_connector_test.go
pkg/util/testutil/testutil.go
pkg/varlog/subscribe_test.go
pkg/varlog/trim_test.go
tests/it/failover/failover_test.go
tests/it/management/vms_test.go
tests/it/testenv.go

This PR relocates the package github.com/kakao/varlog/vtesting to
github.com/kakao/varlog/internal/vtesting as it does not need to be exported.
The package supports flexibility in testing environments by providing features
like a test logger, assertion wait timeout, raft tick, and commit tick of the
metadata repository. However, these parameters are infrequently configured and
can be managed using Go's built-in testing package and helpers.
By moving it to an internal package, we aim to reduce the exposed API surface
and encourage using standard testing tools, eventually leading to the potential
deprecation of the github.com/kakao/varlog/internal/vtesting package. The
package is now being moved to the internal directory without any functional
changes.

refactor(testing): move vtesting to internal/vtesting

---

internal/metarepos/raft_metadata_repository.go
internal/metarepos/raft_metadata_repository_test.go
proto/mrpb/management.pb.go
proto/mrpb/management.proto

This PR makes the MetadataRepository server validate the NodeID while processing
RPCs such as AddPeer and RemovePeer. When the given NodeID is invalid, it
returns the gRPC InvalidArgument status code.
In the case of AddPeer, it prevents unexpected peer addition that has an invalid
NodeID.

fix(metarepos): check the NodeID for adding and removing peers

---

cmd/varlogcli/varlogcli.go
cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/testdata/varlogsn.ct
cmd/varlogsn/varlogsn.go
internal/flags/cluster.go
internal/flags/flags.go

This PR refactors several common CLI flags to enhance their clarity and
usability. The changes include:
- `--storagenode-id`: Specifies the storage node ID.
- `--topic-id`: Specifies the topic ID.
- `--logstream-id`: Specifies the log stream ID.
These adjustments aim to standardize the flag names and improve the overall user
experience.

refactor(flags): rework common CLI flags for improved clarity and usability

---

Makefile

- Updated Makefile to include the coverpkg flag in test_coverage and
test_e2e_local_coverage targets.
- Added commands to remove and recreate coverage directories to ensure clean
coverage data.

ci: add coverpkg flag to improve test coverage reporting

---

pkg/varlog/operations.go

This PR prevents client-side panics in append error handling by correctly accessing error messages from the result struct instead of a nil error variable during partial append failures.
Couldn't find a clean way to simulate partial failures on a specific log stream in the test environment, so test coverage was not added for this fix.

fix: prevent panic on partial append failures

---

proto/snpb/log_io_test.go
proto/snpb/log_stream_reporter.go
proto/snpb/log_stream_reporter_test.go

This PR adds missing tests for proto/snpb.(LogStreamUncommitReport).

test: add missing tests for proto/snpb.(LogStreamUncommitReport)

---

internal/admin/admin.go
proto/snpb/log_io_test.go
proto/snpb/log_stream_reporter.go
proto/snpb/log_stream_reporter_test.go
proto/snpb/metadata.go
tests/it/management/management_test.go

The FindLogStream function in proto/snpb/metadata.go was removed as it was
redundant and no longer needed. The functionality is already covered by the
GetLogStream method.

refactor: remove redundant FindLogStream function

---

proto/snpb/metadata.go
proto/snpb/metadata_test.go

- Add tests for StorageNodeMetadataDescriptor and LogStreamReplicaMetadataDescriptor
- Test methods: ToStorageNodeDescriptor, GetLogStream, Head, and Tail
- Ensure proper coverage for edge cases and nil values

test(proto): add unit tests for metadata descriptors

---

proto/snpb/metadata.go
proto/snpb/metadata_test.go
proto/snpb/replicator.go
proto/snpb/replicator_test.go

- Add comments for SyncPosition.InvalidSyncPosition, SyncPosition.Invalid,
SyncPosition.LessThan, SyncRange.InvalidSyncRange, and SyncRange.Validate
methods.
- Add unit tests for SyncRange validation and invalid cases.

test(proto): add comments and tests for SyncPosition and SyncRange

---

proto/varlogpb/metadata.go
proto/varlogpb/metadata_test.go

- Removed unused functions from metadata.go
- Added comprehensive unit tests for metadata.go and metadata_test.go
- Improved test coverage for various scenarios

test(proto): add and update tests for proto/varlogpb/metadata.go

---

internal/metarepos/raft_metadata_repository.go
internal/metarepos/raft_metadata_repository_test.go

The current implementation of topic unregistration relies on proposeWithGuarantee's retry mechanism when deleting topics with multiple log streams. When a topic containing multiple log streams is unregistered, the control flow returns prematurely after deleting each log stream. This premature return prevents cacheCompleteCB from being called, which proposeWithGuarantee interprets as an incomplete operation that needs to be retried causing the unregistration time to scale linearly with the number of log streams (approximately 100ms per stream) and generates unnecessary consensus overhead.
The fix consolidates all log stream unregistrations into a single Raft proposal by removing the premature return.
With topics containing over 1 billion log streams, state machine operations could still …

fix: unregistering topic translates to multiple redundant Raft proposals

---

.github/workflows/ci.yaml
Makefile
build/Dockerfile
go.mod

Bump Go from 1.23 to 1.24 and golangci-lint.

build(go): bump go from 1.23 to 1.24

---

internal/storagenode/logstream/append.go
internal/storagenode/logstream/replicate_client_test.go
internal/storagenode/logstream/replicate_task.go
internal/storagenode/logstream/replicate_task_test.go

This PR modifies replicate task pool implementation for future refactoring that
will resolve #843.
- Deprecated `newReplicateTask` and `release` functions in favor of new
implementations.
- Added `replicateTaskPool` struct for simplified pool management.
- Updated tests to use the new functions and ensure backward compatibility.

refactor(logstream): deprecate old replicateTask pool management

---

internal/storagenode/logstream/append.go
internal/storagenode/logstream/replicate_client.go
internal/storagenode/logstream/replicate_client_test.go
internal/storagenode/logstream/replicate_task.go
internal/storagenode/logstream/replicate_task_test.go
internal/storagenode/logstream/sequencer.go

Removed the llsnList from the replicateTask to improve performance and simplify
the code. The beginLLSN field is now used instead. This change eliminates the
need to fill llsnList, resulting in a slight performance improvement.

perf(logstream): remove llsnList from replicateTask

---

internal/metarepos/dummy_storagenode_client_factory_impl.go
internal/metarepos/raft_metadata_repository.go
internal/metarepos/report_collector.go
internal/metarepos/report_collector_test.go

This patch makes the report collector handle invalid reports properly. The report collector determines whether a report is invalid based on previously received report.
If valogsn terminates abnormally, the report collector may receive an invalid report and must handle it properly.
Resolves #1011 

fix(metarepos): reportCollector handles invalid report propertly

---

pkg/util/telemetry/metric_provider.go

This commit enables Varlog to support both new and deprecated OpenTelemetry
runtime metrics.
Previously, Varlog only supported the deprecated runtime instrumentation. This
change ensures backward compatibility by simultaneously setting the
`OTEL_GO_X_DEPRECATED_RUNTIME_METRICS` environment variable and using the new
version.
This enhancement allows Varlog to leverage the latest OpenTelemetry features
while maintaining compatibility with older versions, collecting more
comprehensive runtime metrics.

feat(telemetry): Support both new and deprecated OpenTelemetry runtime metrics

---

internal/storagenode/logstream/append.go
internal/storagenode/logstream/append_waitgroup.go
internal/storagenode/logstream/commit_wait_queue_test.go
internal/storagenode/logstream/committer.go
internal/storagenode/logstream/committer_test.go
internal/storagenode/logstream/sequencer.go
internal/storagenode/logstream/sequencer_test.go
internal/storagenode/logstream/writer.go
internal/storagenode/logstream/writer_test.go

This PR reduces append wait groups to a single object for each append batch. The
append wait groups are part of the following structs:
- appendContext
- commitWaitTask
- sequenceTask
Previously, multiple append wait groups existed because each log entry in a
batch had its own wait group. With the changes for issue #843, a single append
wait group now corresponds to an entire batch. This PR consolidates the list of
append wait groups into a single append wait group.
TODO: We are still on the road to resolving #843. The rest of the work mostly
involves cleaning up the code base.

refactor(logstream): consolidate append wait groups into a single object

---

internal/storagenode/logstream/append.go

This PR removes the totalBytes field from the appendContext struct. It modifies
prepareAppendContext to return totalBytes instead of changing the appendContext
struct. Through this PR, the appendContext becomes slightly simple.

refactor: remove totalBytes field from appendContext

---

internal/storagenode/log_server.go
internal/storagenode/storagenode_test.go
pkg/util/telemetry/metric_provider.go
proto/snpb/log_io.pb.go
proto/snpb/log_io.proto

Add validation for empty payloads in the Append RPC. If there is no payload in
the append request, the RPC returns a gRPC status code of InvalidArgument.

feat(storagenode): add empty payload validation

---

cmd/varlogadm/cli.go
cmd/varlogadm/testdata/varlogadm.ct
cmd/varlogmr/metadata_repository.go
cmd/varlogsn/cli.go
cmd/varlogsn/testdata/varlogsn.ct
cmd/varlogsn/varlogsn.go
internal/flags/logger.go
internal/storagenode/log_server.go
internal/storagenode/storagenode_test.go
pkg/util/log/log_test.go
pkg/util/telemetry/metric_provider.go
proto/snpb/log_io.pb.go
proto/snpb/log_io.proto

This PR adds a new flag `--enable-development-mode` to enable development mode
for the logger. If it is true, the logger panics at the DPanic level.

feat: support zap logger's development mode

---

cmd/varlogadm/cli.go
cmd/varlogadm/testdata/varlogadm.ct
cmd/varlogmr/metadata_repository.go
cmd/varlogsn/cli.go
cmd/varlogsn/testdata/varlogsn.ct
cmd/varlogsn/varlogsn.go
internal/flags/logger.go
internal/storagenode/log_server.go
internal/storagenode/logstream/backup_writer.go
internal/storagenode/logstream/backup_writer_test.go
internal/storagenode/logstream/writer.go
internal/storagenode/logstream/writer_test.go
internal/storagenode/storagenode_test.go
pkg/util/log/log_test.go
pkg/util/telemetry/metric_provider.go
proto/snpb/log_io.pb.go
proto/snpb/log_io.proto

This PR adds error handling to prevent panic when an unexpected LLSN is
encountered in backup and primary replicas. If `--enable-development-mode` is
set, panic occurs as before.

fix(storagenode): handle unexpected LLSN errors

---

cmd/varlogadm/cli.go
cmd/varlogadm/testdata/varlogadm.ct
cmd/varlogmr/metadata_repository.go
cmd/varlogsn/cli.go
cmd/varlogsn/testdata/varlogsn.ct
cmd/varlogsn/varlogsn.go
internal/flags/logger.go
internal/storage/commit_context.go
internal/storage/commit_context_test.go
internal/storage/recovery_points.go
internal/storage/recovery_points_test.go
internal/storagenode/log_server.go
internal/storagenode/logstream/backup_writer.go
internal/storagenode/logstream/backup_writer_test.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/writer.go
internal/storagenode/logstream/writer_test.go
internal/storagenode/storagenode_test.go
pkg/util/log/log_test.go
pkg/util/telemetry/metric_provider.go
proto/snpb/log_io.pb.go
proto/snpb/log_io.proto

Enhance logging while bootstrapping log stream replica:
- Add `MarshalLogObject` method to `CommitContext` and `RecoveryPoints` for
structured logging.
- Add logs to print more useful information during data loading on restarts.

refactor(storagenode): add structured logging for recovery points and commit context

---

cmd/varlogadm/cli.go
cmd/varlogadm/testdata/varlogadm.ct
cmd/varlogmr/metadata_repository.go
cmd/varlogsn/cli.go
cmd/varlogsn/testdata/varlogsn.ct
cmd/varlogsn/varlogsn.go
internal/flags/logger.go
internal/metarepos/raft_metadata_repository.go
internal/storage/commit_context.go
internal/storage/commit_context_test.go
internal/storage/recovery_points.go
internal/storage/recovery_points_test.go
internal/storagenode/log_server.go
internal/storagenode/logstream/backup_writer.go
internal/storagenode/logstream/backup_writer_test.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/writer.go
internal/storagenode/logstream/writer_test.go
internal/storagenode/storagenode_test.go
pkg/util/log/log_test.go
pkg/util/telemetry/metric_provider.go
proto/snpb/log_io.pb.go
proto/snpb/log_io.proto

Ensure that unsealing log streams that are already in an appendable state does
not affect the log stream status. Unsealing changes the state of the log stream
to accept Append RPC and creates new replicate channels when it is the primary
replica. Unsealing an already appendable log stream can be harmful since it
creates additional replicate channels even though replicate channels already
exist. This PR addresses this situation.

fix(storagenode): handle unsealing of already appendable log streams

---

cmd/varlogadm/cli.go
cmd/varlogadm/testdata/varlogadm.ct
cmd/varlogmr/metadata_repository.go
cmd/varlogsn/cli.go
cmd/varlogsn/testdata/varlogsn.ct
cmd/varlogsn/varlogsn.go
internal/flags/logger.go
internal/metarepos/raft_metadata_repository.go
internal/storage/commit_context.go
internal/storage/commit_context_test.go
internal/storage/recovery_points.go
internal/storage/recovery_points_test.go
internal/storage/storage.go
internal/storagenode/log_server.go
internal/storagenode/logstream/backup_writer.go
internal/storagenode/logstream/backup_writer_test.go
internal/storagenode/logstream/executor.go
internal/storagenode/logstream/writer.go
internal/storagenode/logstream/writer_test.go
internal/storagenode/storagenode_test.go
pkg/util/log/log_test.go
pkg/util/telemetry/metric_provider.go
proto/snpb/log_io.pb.go
proto/snpb/log_io.proto

This change reduces the verbosity of log messages printed when opening databases
in the storage by conditionally including detailed options only when verbose
mode is enabled.

refactor(storage): reduce verbosity of database opening log messages

---

.github/workflows/ci.yaml
.golangci.yaml
Makefile
internal/admin/admin.go
internal/admin/testing.go
internal/benchmark/report.go
internal/metarepos/dummy_storagenode_client_factory_impl.go
internal/storagenode/client/management_client.go
internal/storagenode/storagenode_test.go
internal/varlogctl/controller_test.go
pkg/varlog/admin.go
pkg/varlog/subscribe.go
pkg/varlogtest/admin.go
pkg/varlogtest/varlogtest_test.go
proto/varlogpb/replica.go
tests/it/testenv.go

This commit updates golangci-lint in Makefile from v1.64.5 to v2.0.2. It also
refactors the code to comply with staticcheck rules QF1008 and QF1003.

ci(lint): bump golangci-lint from v1.64.5 to v2.0.2

---

internal/storagenode/logstream/executor.go
internal/storagenode/storagenode_test.go

This commit fixes a bug that could cause panic during replica sealing in
synchronization. Specifically, if the replica has no log entries (e.g., just
joined or trimmed all), `uncommittedBegin.GLSN` is zero. When the replica
receives a Seal RPC, it can be panicked due to an invalid comparison.
`uncommittedBegin.GLSN-1` is MaxUInt64 since it's a 64-bit unsigned integer.
See
[this code](https://github.com/kakao/varlog/blob/15d90d2b7aed9ebaec57130dc09f3f06b3b750f8/internal/storagenode/logstream/executor.go#L245-L251)
```go
_, _, uncommittedBegin, invalid := lse.lsc.reportCommitBase()
if uncommittedBegin.GLSN-1 > lastCommittedGLSN {
lse.logger.Panic("log stream: seal: metadata repository may be behind of log stream",
zap.Any("local", uncommittedBegin.GLSN-1),
zap.Any("mr", lastCommittedGLSN), …
```

fix(storagenode): prevent panic during replica sealing in synchronization

---

cmd/varlogadm/cli.go
cmd/varlogadm/flags.go
cmd/varlogadm/testdata/varlogadm.ct
internal/admin/admin.go
internal/admin/admin_test.go
internal/admin/config.go
internal/admin/mrmanager/manager.go
internal/admin/snwatcher/config.go
internal/admin/snwatcher/snwatcher.go
internal/admin/snwatcher/snwatcher_test.go
tests/it/cluster/client_test.go
tests/it/config.go
tests/it/failover/failover_test.go
tests/it/management/management_test.go

This change fixes an issue where not all expected logstreams could be sealed within HandleHeartbeatTimeout due to storagenode delaying the response. Also fixes an issue where unexpected logstreams were being sealed by heartbeat false positives. In particular, it increases the priority of seal requests for metarepos so that commit results in metarepos do not pile up even if sealing is delayed.
Resolves #1068 #1069 

fix(admin): fix snwatcher handle heartbeat timeout

---

pkg/varlog/options.go
pkg/varlog/subscribe.go
pkg/varlog/subscribe_test.go

This patch changes the condition for refreshing the subscriber of varlogclient.
The subscriber is created per logstream. If a timeout occurs in the subscribing storagenode, it refreshes so that it can subscribe through another replica. On the other hand, if all logstreams belonging to the topic are subject to change, they are restricted from being replaced. As a result, for a topic with HAFactor=1, even if a timeout occurs in the subscribed storagenode, another replica cannot be selected.
To solve this, the condition was changed so that the subscribers of all logstreams belonging to the topic can be replaced. In addition, metadata requests to metarepos are not made for each refresh. The latest information can be sufficiently received through the refresher running in the background. …

fix(subscriber): fix refresh subscriber

---

internal/storagenode/logstream/executor.go
internal/storagenode/storagenode_test.go

This update resolves a race condition that occurred during concurrent commit and
seal operations in the storage node. The issue was caused by improper state
management, where the seal handler could drain the commit wait queue while the
committer simultaneously processed tasks from it.
This race condition led to a negative counter in `sync.WaitGroup`, causing a
panic. Although the Go race detector did not flag this issue, it was logically a
race condition. The fix involves setting the state to "sealed" before resetting
the internal status of the log stream executor. This ensures proper
synchronization between the committer and seal handler, preventing potential
panics.
Test failure:
```txt
panic: sync: negative WaitGroup counter
goroutine 84102 [running]: …
```

fix(storagenode): prevent panic during concurrent commit & seal ops

---

cmd/varlogadm/cli.go
cmd/varlogadm/testdata/varlogadm.ct
cmd/varlogmr/metadata_repository.go
cmd/varlogsn/cli.go
cmd/varlogsn/testdata/varlogsn.ct
internal/flags/grpc.go
pkg/rpc/server.go

This removes a CLI flag `--grpc-server-max-recv-msg-size`, which specifies the
maximum size for incoming messages. All servers now have no size limit for
receiving and sending messages.

refactor(all): remove --grpc-server-max-recv-msg-size flag

---

pkg/rpc/rpc_conn.go
pkg/rpc/server.go

This commit introduces gRPC keepalive parameters to improve connection
reliability and fault tolerance in Varlog.
On the client side, the `clientKeepaliveInterval` is set to 10s to send periodic
pings, while the `clientKeepaliveTimeout` is set to 1500ms to handle transient
network issues. On the server side, the `serverKeepaliveInterval` is set to
1500ms to reduce unnecessary pings, and the `serverKeepaliveTimeout` is set to
1500ms to reliably detect failed connections.
The timeout values are carefully chosen to balance responsiveness and resource
efficiency, particularly for Ethernet networks. Overall, these improvements
enhance Varlog's fault tolerance by promptly detecting and closing failed
connections, reducing resource usage by minimizing redundant pings, and
improving system …

feat(rpc): add gRPC keepalive parameters for client and server

---

internal/storagenode/logstream/errors.go
internal/storagenode/logstream/executor.go

This change replaces inline error creation with the predefined error constant
`errTooOldCommit` to reduce redundant object creations and improve efficiency.
```
File: varlogsn
Build ID: 738fe0766e67e717e91653e50f8bfbbbfed542a9
Type: alloc_objects
Time: 2025-03-18 12:32:31 KST
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top logstream\.\(\*Executor\)\.Commit
Active filters:
focus=logstream\.\(\*Executor\)\.Commit
Showing nodes accounting for -8053079, 1.70% of 472672864 total
Dropped 4 nodes (cum <= 2363364)
flat  flat%   sum%        cum   cum%
-9796082  2.07%  2.07%   -9796082  2.07%  errors.New (inline)
1743003  0.37%  1.70%   -8053147  1.70%  github.com/kakao/varlog/internal/storagenode/logstream.(*Executor).Commit
```

perf(storagenode): replace inline error with predefined constant

---

internal/storagenode/logstream/executor.go

This change replaces `commitResult.String()` with individual field logging in
`internal/storagenode/logstream.(*Executor).Commit` to prevent commitResult from
escaping to the heap. This change improves memory efficiency by avoiding
unnecessary allocations.

perf(logstream): avoid heap escape of commitResult in Executor.Commit

---

internal/storagenode/reportcommit_server.go

Optimizes memory usage by reusing the CommitResults slice in CommitBatchRequest.
This reduces heap allocations when appending entries, improving performance in
high-throughput scenarios. Since the metadata repository continuously sends
CommitBatch to storage nodes, this change significantly reduces heap
allocations.

perf(storagenode): reuse CommitResults to reduce allocations

---

Makefile
internal/storagenode/replication_server.go
proto/patches/snpb/replicator.pb.go.patch
proto/snpb/replicator.go
proto/snpb/replicator.pb.go
proto/snpb/replicator_test.go

This change improves unmarshaling performance by reusing buffers for
ReplicateRequest in the backup replica.
The protobuf message `github.com/kakao/varlog/proto/snpb.(ReplicateRequest)` has
a slice field - Data (`[][]byte`). The backup replica receives replicated log
entries from the primary replica via the gRPC service
`github.com/kakao/varlog/proto/snpb.(ReplicatorServer).Replicate`, which sends
`ReplicateRequest` messages.
Upon receiving a `ReplicateRequest`, the backup replica unmarshals the message,
which involves growing slices for the Data field. This growth causes copy
overhead whenever the slice capacities need to expand.
To address this, we introduce a new method, `ResetReuse`, for reusing slices
instead of resetting them completely. The `ResetReuse` method shrinks the slice …

perf(sn): reuse buffer for ReplicateRequest unmarshaling

---

internal/metarepos/report_collector.go
internal/reportcommitter/client.go

This commit improves the handling of io.EOF in the report collection process. In
the `reportCollectExecutor`, io.EOF is now treated as a non-error case, allowing
it to reconnect to the storage node on the next attempt instead of closing the
client unnecessarily.
Additionally, the `GetReport` method in the `client` has been simplified by
removing redundant error handling for io.EOF, returning the response directly.
These changes enhance code readability and maintainability without altering the
existing functionality.

refactor(reporter): handle io.EOF gracefully and simplify GetReport logic

---

internal/metarepos/raft_metadata_repository.go
internal/metarepos/report_collector.go
internal/reportcommitter/client.go

The report processing logic has been updated to minimize the time the report
queue lock is held. Previously, the lock was held while creating the `Reports`
object, which could lead to contention. Now, the report queue is copied while
holding the lock, and the `Reports` object is created outside the critical
section. This change improves concurrency and reduces potential bottlenecks.

refactor(metarepos): optimize report processing by reducing lock contention

---

pkg/util/runner/runner_test.go
tests/it/management/management_test.go

This change replaces the custom `testutil.CompareWait` utility with
`require.EventuallyWithT` from the `testify` package in
`pkg/util/runner/runner_test.go` and `tests/it/management/management_test.go`.
This improves readability, simplifies test assertions, and leverages a
well-supported testing library for asserting eventual conditions.

test: replace custom CompareWait with testify's assertions

---

tests/it/failover/failover_test.go

This commit fixes flakiness in TestAdmin_GetStorageNode caused by too short
assertion duration. Previously, the test sometimes failed because the admin
server did not refresh the storage node list within the expected time after a
restart. This change increases the assertion timeout and decreases the admin
server's tick interval, making the test both more reliable and faster.

test: stabilize TestAdmin_GetStorageNode by adjusting timing

---

pkg/mrc/metadata_repository_client.go
pkg/mrc/metadata_repository_management_client.go
pkg/mrc/mrconnector/mr_connector.go

This change eliminates health check logic and related dependencies from
MetadataRepositoryClient, MetadataRepositoryManagementClient, and mr_connector.
Since health check logic is unnecessary in the metadata repository client, it
has been removed. Connection management, including health checks, keepalive, and
reconnection, is handled by gRPC itself. This commit simplifies the metadata
repository client.

refactor(mrc): remove redundant health check from metadata repository client

---

cmd/varlogadm/cli.go
cmd/varlogmr/metadata_repository.go
cmd/varlogsn/varlogsn.go
internal/admin/admin.go
internal/flags/telemetry.go
internal/metarepos/telemetry.go
internal/stats/opentelemetry/config.go
internal/stats/opentelemetry/exporter.go
internal/stats/opentelemetry/metric_provider.go
internal/stats/opentelemetry/semconv.go
internal/storagenode/telemetry/metrics.go

It moves the package from `pkg/util/telemetry` to
`internal/stats/opentelemetry`.

refactor(telemetry): migrate telemetry package to internal/stats/opentelemetry

---

internal/storagenode/logstream/backup_writer.go
internal/storagenode/logstream/backup_writer_test.go
internal/storagenode/logstream/config.go
internal/storagenode/logstream/writer.go
internal/storagenode/logstream/writer_test.go
internal/storagenode/storagenode.go

This change introduces batching of write tasks in primary and backup writers.
The number of tasks is limited by `WithMaxWriteTaskBatchLength`. Since each
write task can already have batched writes, its value is limited from 1 to 3.
This is an internal configuration, thus not exposed as a CLI flag. This commit
sets `WithMaxWriteTaskBatchLength` to 3. We will observe this further and can
change it.

feat(storagenode): enable batching of writes in primary/backup writer

---

bin/start_varlogsn.py
cmd/varlogsn/cli.go
cmd/varlogsn/flags.go
cmd/varlogsn/testdata/varlogsn.ct
cmd/varlogsn/varlogsn.go
internal/storage/config.go
internal/storage/storage.go
internal/storage/storage_test.go

This change makes the storage layer always use separate stores for data and
commit. The experimental flag and related code paths for non-separated stores
have been removed, simplifying configuration and aligning with current usage
patterns.

feat(storage): always separate data and commit stores

---

cmd/varlogsn/varlogsn.go
internal/storage/benchmark_test.go
internal/storage/config.go
internal/storage/recovery_points.go
internal/storage/scanner.go
internal/storage/storage.go
internal/storage/storage_test.go
internal/storage/testing.go

This change renames dataStore to valueStore to clarify its role: it stores user
log entry values. In contrast, commitStore stores the GLSN
(GlobalLogSequenceNumber), which is issued by the metadata repository. The GLSN
acts as the key for the log entry value. While the commitStore could be called
keyStore, we retain the name "commitStore" because it stores global state as
well as GLSNs.
This commit does not change any user-facing features such as the CLI or
environments.

refactor(storage): rename dataStore to valueStore for clarity

---

cmd/varlogsn/varlogsn.go

Previously, the commit store was incorrectly using the data DB's WAL and sync
disable flags (`--storage-datadb-disable-wal` and `--storage-datadb-no-sync`).
This commit updates the code to use the correct flags
(`--storage-commitdb-disable-wal` and `--storage-commitdb-no-sync`) for the
commit store's WAL and sync options, ensuring that these options can be
correctly configured for the commit store as intended.

fix(storagenode): use correct flags for commit store WAL and sync options

---

cmd/varlogsn/varlogsn.go
internal/storage/benchmark_test.go
internal/storage/storage_test.go
internal/storage/store.go
internal/storage/testing.go

This commit clarifies the purpose of the sync option by renaming it to syncWAL.
This makes it explicit that the option controls synchronization of the Pebble
Write-Ahead Log (WAL) to disk. No changes to user-facing CLI flags; existing CLI
usage remains unchanged.

refactor(storage): rename sync option to syncWAL for clarity

---

internal/storage/config.go
internal/storage/opentelemetry.go
internal/storagenode/storagenode.go
internal/storagenode/telemetry/metrics.go

This commit introduces OpenTelemetry histograms to measure various durations
related to batch commits in the store (pebble). This enables tracking long-tail
latencies for each store.

feat(storage,telemetry): add OpenTelemetry batch commit duration metrics for store

---

cmd/varlogsn/flags.go
cmd/varlogsn/varlogsn.go
internal/storage/commit_batch.go
internal/storage/store.go
internal/storage/write_batch.go

This commit introduces the `enable_telemetry` option to the storage store flag.
When enabled, the store collects metrics using OpenTelemetry.
Since collecting metrics in the storage layer can be bursty and costly, it is
disabled by default. Enable this option when internal storage metrics are
needed.

feat(storage): add enable_telemetry option to control metrics recording

---

internal/storagenode/storagenode.go

The closedC channel field was declared in the StorageNode struct but was never
used in the codebase. This commit removes the field to simplify the struct and
reduce unnecessary code. No functional changes are introduced.

refactor(storagenode): remove unused closedC channel from StorageNode struct

---

internal/storage/store.go

This commit removes the explicit call to `Flush` before closing the Pebble DB in
store. When closing, Pebble persists data via the WAL, so flushing memtables is
unnecessary.

refactor(storage): remove unnecessary Flush before DB close

---

pkg/varlog/subscribe.go

The `res` variable in the subscriber's dispatcher loop was escaping to the heap.
This was caused by passing the entire struct to the logger using `zap.Any()`,
which forces an allocation for the interface conversion. This behavior leads to
unnecessary memory allocations.
```go
for res := range p.sleq.recvC() {
if sentErr {
p.logger.Panic("multiple errors in dispatcher", zap.Any("res", res), zap.Error(res.Error))
}
}
```
This commit resolves the issue by logging the individual fields of the `res`
struct. By using `zap.Uint64` and `zap.Error` instead of `zap.Any`, the Go
compiler can keep the `res` variable on the stack, thus preventing the heap
allocation and improving performance.

perf(client,subscribe): reduce heap allocations in the dispatcher loop

---

pkg/varlog/options.go
pkg/varlog/stats.go
pkg/varlog/subscribe.go

This change introduces an observer to the Subscribe API, allowing users to
monitor internal latencies and diagnose performance issues. Previously, the
internal pipeline of the subscribe client was a black box, making it difficult
to pinpoint the cause of performance issues.
With this feature, users can implement the `SubscribeObserver` interface and
register it using the `WithSubscribeObserver` option. The `Observe` method will
be called for each log entry, providing a `SubscribeStats` struct that contains
a detailed breakdown of the time spent in different stages of the internal
pipeline.
The following statistics are provided:
- TransmitEnqueueDuration: The time taken to enqueue a subscribed log entry into
the internal transmit queue.
- TransmitQueueWait: The time a log entry waits in …

feat(varlog): add observer to subscribe API for metrics

---

internal/stats/opentelemetry/metric_provider.go

The initialization logic for OpenTelemetry runtime instrumentation unnecessarily
set the `OTEL_GO_X_DEPRECATED_RUNTIME_METRICS` environment variable. This was a
workaround for older versions of the library to collect both new and deprecated
metrics.
The latest version of the `go.opentelemetry.io/contrib/instrumentation/runtime`
library now produces both sets of metrics when this environment variable is set
to `true`, making the in-code manipulation redundant.
This commit removes the workaround, simplifying the code. To additionally
collect deprecated metrics, users should now set the
`OTEL_GO_X_DEPRECATED_RUNTIME_METRICS=true` environment variable.

refactor(stats/opentelemetry): simplify runtime instrumentation logic
